import { FieldMetadata } from "@/types/enhanced-types";

export const borrowerResumeFieldMetadata: Record<string, FieldMetadata> = {
  // Section 1: Basic Info
  fullLegalName: {
    value: null,
    source: "User Input",
    warnings: [],
    fieldId: "fullLegalName",
    description: "The full legal name of the borrower entity or individual sponsor.",
    primarySource: "User Input",
    backupSource: "Document (Entity Formation)",
    expectedValue: "Text",
    fieldType: "direct",
    dataType: "Text",
    section: "basic-info",
  },
  primaryEntityName: {
    value: null,
    source: "User Input",
    warnings: [],
    fieldId: "primaryEntityName",
    description: "Name of the primary borrowing entity.",
    primarySource: "User Input",
    backupSource: "Document (Org Chart)",
    expectedValue: "Text",
    fieldType: "direct",
    dataType: "Text",
    section: "basic-info",
  },
  primaryEntityStructure: {
    value: null,
    source: "User Input",
    warnings: [],
    fieldId: "primaryEntityStructure",
    description: "Legal structure of the borrowing entity (LLC, LP, etc.).",
    primarySource: "Document (Operating Agmt)",
    backupSource: "User Input",
    expectedValue: "LLC, LP, S-Corp, C-Corp, etc.",
    fieldType: "direct",
    dataType: "Dropdown",
    section: "basic-info",
  },
  contactEmail: {
    value: null,
    source: "User Input",
    warnings: [],
    fieldId: "contactEmail",
    description: "Primary contact email for the borrower.",
    primarySource: "User Input",
    backupSource: "N/A",
    expectedValue: "Email Address",
    fieldType: "direct",
    dataType: "Text",
    section: "basic-info",
  },
  contactPhone: {
    value: null,
    source: "User Input",
    warnings: [],
    fieldId: "contactPhone",
    description: "Primary phone number for the borrower.",
    primarySource: "User Input",
    backupSource: "N/A",
    expectedValue: "Phone Number",
    fieldType: "direct",
    dataType: "Text",
    section: "basic-info",
  },
  contactAddress: {
    value: null,
    source: "User Input",
    warnings: [],
    fieldId: "contactAddress",
    description: "Mailing address for the borrowing entity.",
    primarySource: "User Input",
    backupSource: "Document (Tax Return)",
    expectedValue: "Address String",
    fieldType: "direct",
    dataType: "Text",
    section: "basic-info",
  },

  // Section 2: Experience
  yearsCREExperienceRange: {
    value: null,
    source: "User Input",
    warnings: [],
    fieldId: "yearsCREExperienceRange",
    description: "Number of years the sponsor has been active in CRE.",
    primarySource: "Document (Bio)",
    backupSource: "User Input",
    expectedValue: "0-2, 3-5, 6-10, 11-15, 16+",
    fieldType: "direct",
    dataType: "Dropdown",
    section: "experience",
  },
  assetClassesExperience: {
    value: null,
    source: "User Input",
    warnings: [],
    fieldId: "assetClassesExperience",
    description: "Types of assets the sponsor has developed or managed.",
    primarySource: "Document (Track Record)",
    backupSource: "User Input",
    expectedValue: "Multi-select (Multifamily, Office, etc.)",
    fieldType: "direct",
    dataType: "Multi-select",
    section: "experience",
  },
  geographicMarketsExperience: {
    value: null,
    source: "User Input",
    warnings: [],
    fieldId: "geographicMarketsExperience",
    description: "Regions where the sponsor has experience.",
    primarySource: "Document (Track Record)",
    backupSource: "User Input",
    expectedValue: "Multi-select (Northeast, Southwest, etc.)",
    fieldType: "direct",
    dataType: "Multi-select",
    section: "experience",
  },
  totalDealValueClosedRange: {
    value: null,
    source: "User Input",
    warnings: [],
    fieldId: "totalDealValueClosedRange",
    description: "Total value of real estate transactions closed to date.",
    primarySource: "Document (Track Record)",
    backupSource: "User Input",
    expectedValue: "Range string",
    fieldType: "direct",
    dataType: "Dropdown",
    section: "experience",
  },
  existingLenderRelationships: {
    value: null,
    source: "User Input",
    warnings: [],
    fieldId: "existingLenderRelationships",
    description: "Banks or institutions the borrower has worked with previously.",
    primarySource: "User Input",
    backupSource: "Document (REO Schedule)",
    expectedValue: "Text",
    fieldType: "direct",
    dataType: "Text",
    section: "experience",
  },
  bioNarrative: {
    value: null,
    source: "User Input",
    warnings: [],
    fieldId: "bioNarrative",
    description: "Short biography of the sponsor/company.",
    primarySource: "Document (Marketing Deck)",
    backupSource: "User Input",
    expectedValue: "Paragraph text",
    fieldType: "direct",
    dataType: "Textarea",
    section: "experience",
  },

  // Section 3: Financial Info
  creditScoreRange: {
    value: null,
    source: "User Input",
    warnings: [],
    fieldId: "creditScoreRange",
    description: "Estimated credit score range of the key guarantor.",
    primarySource: "User Input",
    backupSource: "Document (Credit Report)",
    expectedValue: "Range string",
    fieldType: "direct",
    dataType: "Dropdown",
    section: "borrower-financials",
  },
  netWorthRange: {
    value: null,
    source: "User Input",
    warnings: [],
    fieldId: "netWorthRange",
    description: "Estimated net worth range of the key guarantor.",
    primarySource: "Document (PFS)",
    backupSource: "User Input",
    expectedValue: "Range string",
    fieldType: "direct",
    dataType: "Dropdown",
    section: "borrower-financials",
  },
  liquidityRange: {
    value: null,
    source: "User Input",
    warnings: [],
    fieldId: "liquidityRange",
    description: "Estimated liquid assets available.",
    primarySource: "Document (Bank Statements)",
    backupSource: "User Input",
    expectedValue: "Range string",
    fieldType: "direct",
    dataType: "Dropdown",
    section: "borrower-financials",
  },
  bankruptcyHistory: {
    value: null,
    source: "User Input",
    warnings: [],
    fieldId: "bankruptcyHistory",
    description: "History of bankruptcy in the last 7 years.",
    primarySource: "User Input",
    backupSource: "Document (Background Check)",
    expectedValue: "Yes/No",
    fieldType: "direct",
    dataType: "Boolean",
    section: "borrower-financials",
  },
  foreclosureHistory: {
    value: null,
    source: "User Input",
    warnings: [],
    fieldId: "foreclosureHistory",
    description: "History of foreclosure in the last 7 years.",
    primarySource: "User Input",
    backupSource: "Document (Background Check)",
    expectedValue: "Yes/No",
    fieldType: "direct",
    dataType: "Boolean",
    section: "borrower-financials",
  },
  litigationHistory: {
    value: null,
    source: "User Input",
    warnings: [],
    fieldId: "litigationHistory",
    description: "Current or past significant litigation.",
    primarySource: "User Input",
    backupSource: "Document (Background Check)",
    expectedValue: "Yes/No",
    fieldType: "direct",
    dataType: "Boolean",
    section: "borrower-financials",
  },

  // Section 4: Online Presence
  linkedinUrl: {
    value: null,
    source: "User Input",
    warnings: [],
    fieldId: "linkedinUrl",
    description: "Link to LinkedIn profile.",
    primarySource: "User Input",
    backupSource: "N/A",
    expectedValue: "URL",
    fieldType: "direct",
    dataType: "Text",
    section: "online-presence",
  },
  websiteUrl: {
    value: null,
    source: "User Input",
    warnings: [],
    fieldId: "websiteUrl",
    description: "Link to company website.",
    primarySource: "User Input",
    backupSource: "N/A",
    expectedValue: "URL",
    fieldType: "direct",
    dataType: "Text",
    section: "online-presence",
  },

  // Section 5: Principals
  principalLegalName: {
    value: null,
    source: "User Input",
    warnings: [],
    fieldId: "principalLegalName",
    description: "Name of a key principal.",
    primarySource: "User Input",
    backupSource: "Document (Org Chart)",
    expectedValue: "Text",
    fieldType: "direct",
    dataType: "Text",
    section: "principals",
  },
  principalRoleDefault: {
    value: null,
    source: "User Input",
    warnings: [],
    fieldId: "principalRoleDefault",
    description: "Role of the principal (e.g., Sponsor, Guarantor).",
    primarySource: "User Input",
    backupSource: "Document (Org Chart)",
    expectedValue: "Dropdown",
    fieldType: "direct",
    dataType: "Dropdown",
    section: "principals",
  },
  principalEmail: {
    value: null,
    source: "User Input",
    warnings: [],
    fieldId: "principalEmail",
    description: "Email of the principal.",
    primarySource: "User Input",
    backupSource: "N/A",
    expectedValue: "Email",
    fieldType: "direct",
    dataType: "Text",
    section: "principals",
  },
  ownershipPercentage: {
    value: null,
    source: "User Input",
    warnings: [],
    fieldId: "ownershipPercentage",
    description: "Percentage of ownership in the borrowing entity.",
    primarySource: "Document (Org Chart)",
    backupSource: "User Input",
    expectedValue: "Percentage (0-100)",
    fieldType: "direct",
    dataType: "Percent",
    section: "principals",
  },
  principalBio: {
    value: null,
    source: "User Input",
    warnings: [],
    fieldId: "principalBio",
    description: "Short bio for the principal.",
    primarySource: "Document (Bio)",
    backupSource: "User Input",
    expectedValue: "Text",
    fieldType: "direct",
    dataType: "Textarea",
    section: "principals",
  },
};

export const getBorrowerFieldMetadata = (
  fieldId: string
): FieldMetadata | undefined => {
  return borrowerResumeFieldMetadata[fieldId];
};


