// Define the Borrower Resume field metadata configuration
// This mirrors the structure used for Project Resume fields to support
// enhanced features like Autofill sources, tooltips, and rich data.

export const borrowerResumeFieldMetadata: Record<string, FieldMetadata> = {
	// Section 1: Basic Info
	fullLegalName: {
		value: null,
		source: null,
		warnings: [],
		// Additional metadata properties needed for UI rendering logic
		// These are typed via augmentation or loose usage in components
		fieldId: "fullLegalName",
		description:
			"The full legal name of the borrower entity or individual sponsor.",
		primarySource: "User Input",
		backupSource: "Document (Entity Formation)",
		expectedValue: "Text",
		fieldType: "direct",
		dataType: "Text",
		section: "basic-info",
	} as any,
	primaryEntityName: {
		value: null,
		source: null,
		warnings: [],
		fieldId: "primaryEntityName",
		description: "Name of the primary borrowing entity.",
		primarySource: "User Input",
		backupSource: "Document (Org Chart)",
		expectedValue: "Text",
		fieldType: "direct",
		dataType: "Text",
		section: "basic-info",
	} as any,
	primaryEntityStructure: {
		value: null,
		source: null,
		warnings: [],
		fieldId: "primaryEntityStructure",
		description: "Legal structure of the borrowing entity (LLC, LP, etc.).",
		primarySource: "Document (Operating Agmt)",
		backupSource: "User Input",
		expectedValue: "LLC, LP, S-Corp, C-Corp, etc.",
		fieldType: "direct",
		dataType: "Dropdown",
		section: "basic-info",
	} as any,
	contactEmail: {
		value: null,
		source: null,
		warnings: [],
		fieldId: "contactEmail",
		description: "Primary contact email for the borrower.",
		primarySource: "User Input",
		backupSource: "N/A",
		expectedValue: "Email Address",
		fieldType: "direct",
		dataType: "Text",
		section: "basic-info",
	} as any,
	contactPhone: {
		value: null,
		source: null,
		warnings: [],
		fieldId: "contactPhone",
		description: "Primary phone number for the borrower.",
		primarySource: "User Input",
		backupSource: "N/A",
		expectedValue: "Phone Number",
		fieldType: "direct",
		dataType: "Text",
		section: "basic-info",
	} as any,
	contactAddress: {
		value: null,
		source: null,
		warnings: [],
		fieldId: "contactAddress",
		description: "Mailing address for the borrowing entity.",
		primarySource: "User Input",
		backupSource: "Document (Tax Return)",
		expectedValue: "Address String",
		fieldType: "direct",
		dataType: "Text",
		section: "basic-info",
	} as any,

	// Section 2: Experience
	yearsCREExperienceRange: {
		value: null,
		source: null,
		warnings: [],
		fieldId: "yearsCREExperienceRange",
		description: "Number of years the sponsor has been active in CRE.",
		primarySource: "Document (Bio)",
		backupSource: "User Input",
		expectedValue: "0-2, 3-5, 6-10, 11-15, 16+",
		fieldType: "direct",
		dataType: "Dropdown",
		section: "experience",
	} as any,
	assetClassesExperience: {
		value: null,
		source: null,
		warnings: [],
		fieldId: "assetClassesExperience",
		description: "Types of assets the sponsor has developed or managed.",
		primarySource: "Document (Track Record)",
		backupSource: "User Input",
		expectedValue: "Multi-select (Multifamily, Office, etc.)",
		fieldType: "direct",
		dataType: "Multi-select",
		section: "experience",
	} as any,
	geographicMarketsExperience: {
		value: null,
		source: null,
		warnings: [],
		fieldId: "geographicMarketsExperience",
		description: "Regions where the sponsor has experience.",
		primarySource: "Document (Track Record)",
		backupSource: "User Input",
		expectedValue: "Multi-select (Northeast, Southwest, etc.)",
		fieldType: "direct",
		dataType: "Multi-select",
		section: "experience",
	} as any,
	totalDealValueClosedRange: {
		value: null,
		source: null,
		warnings: [],
		fieldId: "totalDealValueClosedRange",
		description: "Total value of real estate transactions closed to date.",
		primarySource: "Document (Track Record)",
		backupSource: "User Input",
		expectedValue: "Range string",
		fieldType: "direct",
		dataType: "Dropdown",
		section: "experience",
	} as any,
	existingLenderRelationships: {
		value: null,
		source: null,
		warnings: [],
		fieldId: "existingLenderRelationships",
		description:
			"Banks or institutions the borrower has worked with previously.",
		primarySource: "User Input",
		backupSource: "Document (REO Schedule)",
		expectedValue: "Text",
		fieldType: "direct",
		dataType: "Text",
		section: "experience",
	} as any,
	bioNarrative: {
		value: null,
		source: null,
		warnings: [],
		fieldId: "bioNarrative",
		description: "Short biography of the sponsor/company.",
		primarySource: "Document (Marketing Deck)",
		backupSource: "User Input",
		expectedValue: "Paragraph text",
		fieldType: "direct",
		dataType: "Textarea",
		section: "experience",
	} as any,

	// Section 3: Financial Info
	creditScoreRange: {
		value: null,
		source: null,
		warnings: [],
		fieldId: "creditScoreRange",
		description: "Estimated credit score range of the key guarantor.",
		primarySource: "User Input",
		backupSource: "Document (Credit Report)",
		expectedValue: "Range string",
		fieldType: "direct",
		dataType: "Dropdown",
		section: "borrower-financials",
	} as any,
	netWorthRange: {
		value: null,
		source: null,
		warnings: [],
		fieldId: "netWorthRange",
		description: "Estimated net worth range of the key guarantor.",
		primarySource: "Document (PFS)",
		backupSource: "User Input",
		expectedValue: "Range string",
		fieldType: "direct",
		dataType: "Dropdown",
		section: "borrower-financials",
	} as any,
	liquidityRange: {
		value: null,
		source: null,
		warnings: [],
		fieldId: "liquidityRange",
		description: "Estimated liquid assets available.",
		primarySource: "Document (Bank Statements)",
		backupSource: "User Input",
		expectedValue: "Range string",
		fieldType: "direct",
		dataType: "Dropdown",
		section: "borrower-financials",
	} as any,
	bankruptcyHistory: {
		value: null,
		source: null,
		warnings: [],
		fieldId: "bankruptcyHistory",
		description: "History of bankruptcy in the last 7 years.",
		primarySource: "User Input",
		backupSource: "Document (Background Check)",
		expectedValue: "Yes/No",
		fieldType: "direct",
		dataType: "Boolean",
		section: "borrower-financials",
	} as any,
	foreclosureHistory: {
		value: null,
		source: null,
		warnings: [],
		fieldId: "foreclosureHistory",
		description: "History of foreclosure in the last 7 years.",
		primarySource: "User Input",
		backupSource: "Document (Background Check)",
		expectedValue: "Yes/No",
		fieldType: "direct",
		dataType: "Boolean",
		section: "borrower-financials",
	} as any,
	litigationHistory: {
		value: null,
		source: null,
		warnings: [],
		fieldId: "litigationHistory",
		description: "Current or past significant litigation.",
		primarySource: "User Input",
		backupSource: "Document (Background Check)",
		expectedValue: "Yes/No",
		fieldType: "direct",
		dataType: "Boolean",
		section: "borrower-financials",
	} as any,

	// Section 4: Online Presence
	linkedinUrl: {
		value: null,
		source: null,
		warnings: [],
		fieldId: "linkedinUrl",
		description: "Link to LinkedIn profile.",
		primarySource: "User Input",
		backupSource: "N/A",
		expectedValue: "URL",
		fieldType: "direct",
		dataType: "Text",
		section: "online-presence",
	} as any,
	websiteUrl: {
		value: null,
		source: null,
		warnings: [],
		fieldId: "websiteUrl",
		description: "Link to company website.",
		primarySource: "User Input",
		backupSource: "N/A",
		expectedValue: "URL",
		fieldType: "direct",
		dataType: "Text",
		section: "online-presence",
	} as any,

	// Section 5: Principals (Metadata for individual fields within array items)
	principalLegalName: {
		value: null,
		source: null,
		warnings: [],
		fieldId: "principalLegalName",
		description: "Name of a key principal.",
		primarySource: "User Input",
		backupSource: "Document (Org Chart)",
		expectedValue: "Text",
		fieldType: "direct",
		dataType: "Text",
		section: "principals",
	} as any,
	principalRoleDefault: {
		value: null,
		source: null,
		warnings: [],
		fieldId: "principalRoleDefault",
		description: "Role of the principal (e.g., Sponsor, Guarantor).",
		primarySource: "User Input",
		backupSource: "Document (Org Chart)",
		expectedValue: "Dropdown",
		fieldType: "direct",
		dataType: "Dropdown",
		section: "principals",
	} as any,
	principalEmail: {
		value: null,
		source: null,
		warnings: [],
		fieldId: "principalEmail",
		description: "Email of the principal.",
		primarySource: "User Input",
		backupSource: "N/A",
		expectedValue: "Email",
		fieldType: "direct",
		dataType: "Text",
		section: "principals",
	} as any,
	ownershipPercentage: {
		value: null,
		source: null,
		warnings: [],
		fieldId: "ownershipPercentage",
		description: "Percentage of ownership in the borrowing entity.",
		primarySource: "Document (Org Chart)",
		backupSource: "User Input",
		expectedValue: "Percentage (0-100)",
		fieldType: "direct",
		dataType: "Percent",
		section: "principals",
	} as any,
	principalBio: {
		value: null,
		source: null,
		warnings: [],
		fieldId: "principalBio",
		description: "Short bio for the principal.",
		primarySource: "Document (Bio)",
		backupSource: "User Input",
		expectedValue: "Text",
		fieldType: "direct",
		dataType: "Textarea",
		section: "principals",
	} as any,

	// Container field for the principals array itself
	principals: {
		value: null,
		source: null,
		warnings: [],
		fieldId: "principals",
		description: "List of key principals and their details.",
		primarySource: "User Input",
		backupSource: "Document (Org Chart)",
		expectedValue: "Array of Principal objects",
		fieldType: "direct",
		dataType: "Table",
		section: "principals",
	} as any,
};

// Type guard/helper
export interface FieldMetadata {
	value: any;
	source: string | null;
	sources?: string[]; // Array of all sources
	warnings: string[];
	original_value?: any;

	// Extended UI metadata
	fieldId: string;
	description: string;
	primarySource: string;
	backupSource?: string;
	expectedValue: string;
	fieldType: "direct" | "derived";
	dataType?: string;
	section: string;
}