// src/lib/project-resume-field-metadata.ts
// Field metadata configuration for Project Resume fields based on Hoque_Data.md

export type FieldSource = 'user-input' | 'document' | 'derived' | 'external' | 'auto-populated';
export type FieldType = 'direct' | 'derived';

export interface FieldMetadata {
  fieldId: string;
  description: string;
  primarySource: string;
  backupSource?: string;
  expectedValue: string;
  fieldType: FieldType;
  dataType?: string;
  section: string;
}

export const projectResumeFieldMetadata: Record<string, FieldMetadata> = {
  // Section 1: Project Identification & Basic Info
  projectName: {
    fieldId: 'projectName',
    description: 'The official name of your project. This is used for identification and marketing purposes.',
    primarySource: 'User Input',
    backupSource: 'N/A',
    expectedValue: 'e.g., SoGood Apartments',
    fieldType: 'direct',
    dataType: 'Text',
    section: 'basic-info',
  },
  propertyAddressStreet: {
    fieldId: 'propertyAddressStreet',
    description: 'The street address of the property. On selection, this will trigger backend API jobs to auto-populate related fields.',
    primarySource: 'User Input (Google Places Autocomplete)',
    backupSource: 'External (Google Maps API)',
    expectedValue: 'e.g., 2300 Hickory St',
    fieldType: 'direct',
    dataType: 'Address',
    section: 'basic-info',
  },
  propertyAddressCity: {
    fieldId: 'propertyAddressCity',
    description: 'City where the property is located. This is auto-populated from the address selection.',
    primarySource: 'Derived (Extract from Address)',
    backupSource: 'External (Google Maps API)',
    expectedValue: 'e.g., Dallas',
    fieldType: 'derived',
    dataType: 'Text',
    section: 'basic-info',
  },
  propertyAddressState: {
    fieldId: 'propertyAddressState',
    description: 'State where the property is located. This is auto-populated from the address selection.',
    primarySource: 'Derived (Extract from Address)',
    backupSource: 'External (Google Maps API)',
    expectedValue: '2-letter state code, e.g., TX',
    fieldType: 'derived',
    dataType: 'Dropdown',
    section: 'basic-info',
  },
  propertyAddressZip: {
    fieldId: 'propertyAddressZip',
    description: 'ZIP code of the property location. This is auto-populated from the address selection.',
    primarySource: 'Derived (Extract from Address)',
    backupSource: 'External (USPS API)',
    expectedValue: 'e.g., 75215',
    fieldType: 'derived',
    dataType: 'Numeric',
    section: 'basic-info',
  },
  propertyAddressCounty: {
    fieldId: 'propertyAddressCounty',
    description: 'County where the property is located. Used for tax jurisdiction determination.',
    primarySource: 'Document (Title Commitment)',
    backupSource: 'External (Census TIGERweb)',
    expectedValue: 'e.g., Dallas County',
    fieldType: 'direct',
    dataType: 'Text',
    section: 'basic-info',
  },
  parcelNumber: {
    fieldId: 'parcelNumber',
    description: 'Legal property identifier(s). Allow multiple comma-separated values if the property spans multiple parcels.',
    primarySource: 'Document (ALTA Survey)',
    backupSource: 'External (Regrid API)',
    expectedValue: 'e.g., 000472000A01B0100',
    fieldType: 'direct',
    dataType: 'Text',
    section: 'basic-info',
  },
  zoningDesignation: {
    fieldId: 'zoningDesignation',
    description: 'Zoning designation that determines development rights and building requirements.',
    primarySource: 'Document (Zoning Letter)',
    backupSource: 'External (Zoneomics API)',
    expectedValue: 'e.g., PD317',
    fieldType: 'direct',
    dataType: 'Text',
    section: 'basic-info',
  },
  projectType: {
    fieldId: 'projectType',
    description: 'Type(s) of project. You can select multiple types if the project is mixed-use.',
    primarySource: 'User Input',
    backupSource: 'N/A',
    expectedValue: 'Multifamily, Mixed-Use, Retail, Office (multi-select)',
    fieldType: 'direct',
    dataType: 'Multi-select',
    section: 'basic-info',
  },
  assetType: {
    fieldId: 'assetType',
    description: 'Primary asset type classification. This helps match your project with appropriate lenders and determines loan product eligibility.',
    primarySource: 'User Input',
    backupSource: 'N/A',
    expectedValue: 'Multifamily, Office, Retail, Industrial, Mixed-Use, etc.',
    fieldType: 'direct',
    dataType: 'Dropdown',
    section: 'basic-info',
  },
  primaryAssetClass: {
    fieldId: 'primaryAssetClass',
    description: 'Primary asset class for loan product matching. This determines the type of lenders who will see your project.',
    primarySource: 'User Input',
    backupSource: 'N/A',
    expectedValue: 'e.g., Multifamily',
    fieldType: 'direct',
    dataType: 'Dropdown',
    section: 'basic-info',
  },
  projectPhase: {
    fieldId: 'projectPhase',
    description: 'Current phase or deal type of the project. This indicates what stage the project is in and what type of financing is needed.',
    primarySource: 'User Input',
    backupSource: 'N/A',
    expectedValue: 'Acquisition, Refinance, Construction, Bridge, Development, Value-Add, Other',
    fieldType: 'direct',
    dataType: 'Dropdown',
    section: 'basic-info',
  },
  projectDescription: {
    fieldId: 'projectDescription',
    description: 'A brief narrative description of the project, its location, and key features. This helps lenders understand the project context.',
    primarySource: 'User Input',
    backupSource: 'N/A',
    expectedValue: 'Text description, e.g., "Ground-up development of Building B within the SoGood master plan..."',
    fieldType: 'direct',
    dataType: 'Textarea',
    section: 'basic-info',
  },
  constructionType: {
    fieldId: 'constructionType',
    description: 'Type of construction work. This affects risk profile and lender preferences.',
    primarySource: 'Document (Arch Plans)',
    backupSource: 'User Input',
    expectedValue: 'Ground-Up, Renovation, Adaptive Reuse',
    fieldType: 'direct',
    dataType: 'Radio',
    section: 'basic-info',
  },
  groundbreakingDate: {
    fieldId: 'groundbreakingDate',
    description: 'Planned date for construction to begin.',
    primarySource: 'Document (Construction Schedule)',
    backupSource: 'User Input',
    expectedValue: 'Date, e.g., Q3 2025',
    fieldType: 'direct',
    dataType: 'Date',
    section: 'basic-info',
  },
  completionDate: {
    fieldId: 'completionDate',
    description: 'Expected project completion date.',
    primarySource: 'Document (Construction Schedule)',
    backupSource: 'User Input',
    expectedValue: 'Date, e.g., Q3 2027',
    fieldType: 'direct',
    dataType: 'Date',
    section: 'basic-info',
  },
  totalDevelopmentCost: {
    fieldId: 'totalDevelopmentCost',
    description: 'Total development cost (TDC). This is automatically calculated as the sum of all budget line items.',
    primarySource: 'Derived (Sum of Budget)',
    backupSource: 'Document (Dev Budget)',
    expectedValue: 'Currency, e.g., $29,800,000',
    fieldType: 'derived',
    dataType: 'Currency',
    section: 'basic-info',
  },
  loanAmountRequested: {
    fieldId: 'loanAmountRequested',
    description: 'The loan amount you are requesting from the lender. This is the primary ask in your financing request.',
    primarySource: 'Document (Sources & Uses)',
    backupSource: 'User Input',
    expectedValue: 'Currency, e.g., $18,000,000',
    fieldType: 'direct',
    dataType: 'Currency',
    section: 'loan-info',
  },
  loanType: {
    fieldId: 'loanType',
    description: 'Type of loan product you are seeking. This determines which lenders will see your project and what loan products they can offer.',
    primarySource: 'User Input',
    backupSource: 'N/A',
    expectedValue: 'Senior Debt, Mezzanine, Preferred Equity, Common Equity, JV Equity, Other',
    fieldType: 'direct',
    dataType: 'Dropdown',
    section: 'loan-info',
  },
  targetLtvPercent: {
    fieldId: 'targetLtvPercent',
    description: 'Target Loan-to-Value ratio as a percentage. This is the loan amount divided by the property value.',
    primarySource: 'Document (Term Sheet)',
    backupSource: 'User Input',
    expectedValue: 'Percentage, e.g., 70%',
    fieldType: 'direct',
    dataType: 'Percent',
    section: 'loan-info',
  },
  targetLtcPercent: {
    fieldId: 'targetLtcPercent',
    description: 'Target Loan-to-Cost ratio as a percentage. Used for construction/development projects. This is the loan amount divided by total project cost.',
    primarySource: 'Document (Term Sheet)',
    backupSource: 'User Input',
    expectedValue: 'Percentage, e.g., 80%',
    fieldType: 'direct',
    dataType: 'Percent',
    section: 'loan-info',
  },
  amortizationYears: {
    fieldId: 'amortizationYears',
    description: 'Amortization period in years. This is the number of years over which the loan principal is repaid.',
    primarySource: 'Document (Term Sheet)',
    backupSource: 'User Input',
    expectedValue: 'Number of years, e.g., 30',
    fieldType: 'direct',
    dataType: 'Integer',
    section: 'loan-info',
  },
  interestOnlyPeriodMonths: {
    fieldId: 'interestOnlyPeriodMonths',
    description: 'Number of months during which only interest payments are required (no principal payments).',
    primarySource: 'Document (Term Sheet)',
    backupSource: 'User Input',
    expectedValue: 'Number of months, e.g., 36',
    fieldType: 'direct',
    dataType: 'Integer',
    section: 'loan-info',
  },
  interestRateType: {
    fieldId: 'interestRateType',
    description: 'Type of interest rate structure for the loan.',
    primarySource: 'Document (Term Sheet)',
    backupSource: 'User Input',
    expectedValue: 'Fixed, Floating, Not Specified',
    fieldType: 'direct',
    dataType: 'Dropdown',
    section: 'loan-info',
  },
  targetCloseDate: {
    fieldId: 'targetCloseDate',
    description: 'Target date for loan closing. This helps lenders understand your timeline and urgency.',
    primarySource: 'Document (Term Sheet)',
    backupSource: 'User Input',
    expectedValue: 'Date, e.g., 2025-08-15',
    fieldType: 'direct',
    dataType: 'Date',
    section: 'loan-info',
  },
  recoursePreference: {
    fieldId: 'recoursePreference',
    description: 'Your preference for recourse structure. Full recourse means personal guarantee, non-recourse means no personal guarantee.',
    primarySource: 'Document (Term Sheet)',
    backupSource: 'User Input',
    expectedValue: 'Full Recourse, Partial Recourse, Non-Recourse, Flexible',
    fieldType: 'direct',
    dataType: 'Dropdown',
    section: 'loan-info',
  },
  useOfProceeds: {
    fieldId: 'useOfProceeds',
    description: 'Description of how the loan proceeds will be used. This helps lenders understand the purpose and risk profile of the loan.',
    primarySource: 'Document (Sources & Uses)',
    backupSource: 'User Input',
    expectedValue: 'Text description, e.g., "Land acquisition, vertical construction, soft costs..."',
    fieldType: 'direct',
    dataType: 'Textarea',
    section: 'loan-info',
  },
  requestedLoanTerm: {
    fieldId: 'requestedLoanTerm',
    description: 'Requested loan term length.',
    primarySource: 'Document (Term Sheet)',
    backupSource: 'User Input',
    expectedValue: 'Text, e.g., "2 years"',
    fieldType: 'direct',
    dataType: 'Text',
    section: 'loan-info',
  },
  masterPlanName: {
    fieldId: 'masterPlanName',
    description: 'Name of the master planned development if this project is part of a larger development.',
    primarySource: 'Document (Marketing Brochure)',
    backupSource: 'User Input',
    expectedValue: 'e.g., SoGood Master Planned Development',
    fieldType: 'direct',
    dataType: 'Text',
    section: 'basic-info',
  },
  phaseNumber: {
    fieldId: 'phaseNumber',
    description: 'Phase number if this project is part of a phased development.',
    primarySource: 'Document (Site Plan)',
    backupSource: 'User Input',
    expectedValue: 'e.g., Building B',
    fieldType: 'direct',
    dataType: 'Numeric',
    section: 'basic-info',
  },
  
  // Section 2: Property Specifications
  totalResidentialUnits: {
    fieldId: 'totalResidentialUnits',
    description: 'Total number of residential units. This is automatically calculated from the unit mix.',
    primarySource: 'Derived (Sum of Unit Mix)',
    backupSource: 'Document (Arch Plans)',
    expectedValue: 'Integer, e.g., 116',
    fieldType: 'derived',
    dataType: 'Integer',
    section: 'property-specs',
  },
  totalResidentialNRSF: {
    fieldId: 'totalResidentialNRSF',
    description: 'Total net rentable square feet for residential units. This is automatically calculated from unit sizes.',
    primarySource: 'Derived (Sum of Unit SF)',
    backupSource: 'Document (Arch Plans)',
    expectedValue: 'Integer, e.g., 59,520',
    fieldType: 'derived',
    dataType: 'Integer',
    section: 'property-specs',
  },
  averageUnitSize: {
    fieldId: 'averageUnitSize',
    description: 'Average unit size. This is automatically calculated as NRSF divided by number of units.',
    primarySource: 'Derived (NRSF / Units)',
    backupSource: 'N/A',
    expectedValue: 'Integer, e.g., 513 SF',
    fieldType: 'derived',
    dataType: 'Integer',
    section: 'property-specs',
  },
  totalCommercialGRSF: {
    fieldId: 'totalCommercialGRSF',
    description: 'Total gross rentable square feet for commercial space.',
    primarySource: 'Document (Arch Plans)',
    backupSource: 'User Input',
    expectedValue: 'Integer, e.g., 49,569',
    fieldType: 'direct',
    dataType: 'Integer',
    section: 'property-specs',
  },
  grossBuildingArea: {
    fieldId: 'grossBuildingArea',
    description: 'Total gross building area including all floors.',
    primarySource: 'Document (Arch Plans)',
    backupSource: 'User Input',
    expectedValue: 'Integer, e.g., 127,406',
    fieldType: 'direct',
    dataType: 'Integer',
    section: 'property-specs',
  },
  numberOfStories: {
    fieldId: 'numberOfStories',
    description: 'Number of stories in the building.',
    primarySource: 'Document (Elevations)',
    backupSource: 'User Input',
    expectedValue: 'Integer, e.g., 6',
    fieldType: 'direct',
    dataType: 'Integer',
    section: 'property-specs',
  },
  buildingType: {
    fieldId: 'buildingType',
    description: 'Classification of the building type.',
    primarySource: 'Document (Arch Plans)',
    backupSource: 'User Input',
    expectedValue: 'High-rise, Mid-rise, Garden, Podium',
    fieldType: 'direct',
    dataType: 'Dropdown',
    section: 'property-specs',
  },
  parkingSpaces: {
    fieldId: 'parkingSpaces',
    description: 'Total number of parking spaces.',
    primarySource: 'Document (Site Plan)',
    backupSource: 'User Input',
    expectedValue: 'Integer, e.g., 180',
    fieldType: 'direct',
    dataType: 'Integer',
    section: 'property-specs',
  },
  parkingRatio: {
    fieldId: 'parkingRatio',
    description: 'Parking spaces per unit. This is automatically calculated as spaces divided by units.',
    primarySource: 'Derived (Spaces / Units)',
    backupSource: 'N/A',
    expectedValue: 'Decimal, e.g., 1.55',
    fieldType: 'derived',
    dataType: 'Decimal',
    section: 'property-specs',
  },
  parkingType: {
    fieldId: 'parkingType',
    description: 'Type of parking configuration.',
    primarySource: 'Document (Site Plan)',
    backupSource: 'User Input',
    expectedValue: 'Surface, Structured, Underground (checkbox)',
    fieldType: 'direct',
    dataType: 'Checkbox',
    section: 'property-specs',
  },
  amenityList: {
    fieldId: 'amenityList',
    description: 'List of building amenities available to residents.',
    primarySource: 'Document (Arch Plans)',
    backupSource: 'User Input',
    expectedValue: 'Pool, Gym, Coworking, etc. (multi-select)',
    fieldType: 'direct',
    dataType: 'Checklist',
    section: 'property-specs',
  },
  amenitySF: {
    fieldId: 'amenitySF',
    description: 'Total square footage dedicated to amenities.',
    primarySource: 'Derived (Sum of Areas)',
    backupSource: 'Document (Arch Plans)',
    expectedValue: 'Integer, e.g., 35,264 SF',
    fieldType: 'direct',
    dataType: 'Integer',
    section: 'property-specs',
  },
  
  // Section 3: Financial Details
  landAcquisition: {
    fieldId: 'landAcquisition',
    description: 'Cost of land acquisition.',
    primarySource: 'Document (Purchase Agmt)',
    backupSource: 'User Input',
    expectedValue: 'Currency, e.g., $6,000,000',
    fieldType: 'direct',
    dataType: 'Currency',
    section: 'financial-details',
  },
  baseConstruction: {
    fieldId: 'baseConstruction',
    description: 'Base construction cost (hard costs).',
    primarySource: 'Document (Budget)',
    backupSource: 'User Input',
    expectedValue: 'Currency, e.g., $16,950,000',
    fieldType: 'direct',
    dataType: 'Currency',
    section: 'financial-details',
  },
  contingency: {
    fieldId: 'contingency',
    description: 'Construction contingency as a risk buffer.',
    primarySource: 'Document (Budget)',
    backupSource: 'Derived (5% of Hard Cost)',
    expectedValue: 'Currency, e.g., $847,500',
    fieldType: 'direct',
    dataType: 'Currency',
    section: 'financial-details',
  },
  ffe: {
    fieldId: 'ffe',
    description: 'Furniture, Fixtures & Equipment costs.',
    primarySource: 'Document (Budget)',
    backupSource: 'User Input',
    expectedValue: 'Currency, e.g., $580,000',
    fieldType: 'direct',
    dataType: 'Currency',
    section: 'financial-details',
  },
  constructionFees: {
    fieldId: 'constructionFees',
    description: 'General contractor fees and general conditions.',
    primarySource: 'Document (Budget)',
    backupSource: 'User Input',
    expectedValue: 'Currency, e.g., $174,000',
    fieldType: 'direct',
    dataType: 'Currency',
    section: 'financial-details',
  },
  aeFees: {
    fieldId: 'aeFees',
    description: 'Architecture & Engineering fees.',
    primarySource: 'Document (Budget)',
    backupSource: 'User Input',
    expectedValue: 'Currency, e.g., $859,800',
    fieldType: 'direct',
    dataType: 'Currency',
    section: 'financial-details',
  },
  thirdPartyReports: {
    fieldId: 'thirdPartyReports',
    description: 'Costs for third-party reports (environmental, appraisal, etc.).',
    primarySource: 'Document (Budget)',
    backupSource: 'User Input',
    expectedValue: 'Currency, e.g., $50,000',
    fieldType: 'direct',
    dataType: 'Currency',
    section: 'financial-details',
  },
  legalAndOrg: {
    fieldId: 'legalAndOrg',
    description: 'Legal and organizational fees.',
    primarySource: 'Document (Budget)',
    backupSource: 'User Input',
    expectedValue: 'Currency, e.g., $50,000',
    fieldType: 'direct',
    dataType: 'Currency',
    section: 'financial-details',
  },
  titleAndRecording: {
    fieldId: 'titleAndRecording',
    description: 'Title insurance and recording fees.',
    primarySource: 'Document (Budget)',
    backupSource: 'User Input',
    expectedValue: 'Currency, e.g., $75,000',
    fieldType: 'direct',
    dataType: 'Currency',
    section: 'financial-details',
  },
  taxesDuringConstruction: {
    fieldId: 'taxesDuringConstruction',
    description: 'Property taxes during construction period.',
    primarySource: 'Document (Budget)',
    backupSource: 'User Input',
    expectedValue: 'Currency, e.g., $20,000',
    fieldType: 'direct',
    dataType: 'Currency',
    section: 'financial-details',
  },
  workingCapital: {
    fieldId: 'workingCapital',
    description: 'Operating cash reserve for construction period.',
    primarySource: 'Document (Budget)',
    backupSource: 'User Input',
    expectedValue: 'Currency, e.g., $1,900,000',
    fieldType: 'direct',
    dataType: 'Currency',
    section: 'financial-details',
  },
  developerFee: {
    fieldId: 'developerFee',
    description: 'Developer fee or sponsor profit.',
    primarySource: 'Document (Budget)',
    backupSource: 'Derived (4% of TDC)',
    expectedValue: 'Currency, e.g., $678,000',
    fieldType: 'direct',
    dataType: 'Currency',
    section: 'financial-details',
  },
  pfcStructuringFee: {
    fieldId: 'pfcStructuringFee',
    description: 'PFC structuring fee (specific to tax exemption deals).',
    primarySource: 'Document (Budget)',
    backupSource: 'User Input',
    expectedValue: 'Currency, e.g., $116,000',
    fieldType: 'direct',
    dataType: 'Currency',
    section: 'financial-details',
  },
  loanFees: {
    fieldId: 'loanFees',
    description: 'Loan origination fees.',
    primarySource: 'Document (Budget)',
    backupSource: 'Derived (1-2% of Loan)',
    expectedValue: 'Currency, e.g., $360,000',
    fieldType: 'direct',
    dataType: 'Currency',
    section: 'financial-details',
  },
  interestReserve: {
    fieldId: 'interestReserve',
    description: 'Interest reserve for debt service during construction.',
    primarySource: 'Document (Budget)',
    backupSource: 'Derived (Calculated)',
    expectedValue: 'Currency, e.g., $1,147,500',
    fieldType: 'direct',
    dataType: 'Currency',
    section: 'financial-details',
  },
  seniorLoanAmount: {
    fieldId: 'seniorLoanAmount',
    description: 'Senior loan amount in the capital stack.',
    primarySource: 'Document (Sources & Uses)',
    backupSource: 'User Input',
    expectedValue: 'Currency, e.g., $18,000,000',
    fieldType: 'direct',
    dataType: 'Currency',
    section: 'financial-details',
  },
  sponsorEquity: {
    fieldId: 'sponsorEquity',
    description: 'Sponsor equity contribution.',
    primarySource: 'Document (Sources & Uses)',
    backupSource: 'Derived (TDC - Loan)',
    expectedValue: 'Currency, e.g., $11,800,000',
    fieldType: 'direct',
    dataType: 'Currency',
    section: 'financial-details',
  },
  interestRate: {
    fieldId: 'interestRate',
    description: 'Interest rate for the loan.',
    primarySource: 'Document (Term Sheet)',
    backupSource: 'User Input',
    expectedValue: 'Percentage, e.g., 8.00%',
    fieldType: 'direct',
    dataType: 'Percent',
    section: 'loan-terms',
  },
  underwritingRate: {
    fieldId: 'underwritingRate',
    description: 'Underwriting/stress test interest rate.',
    primarySource: 'Document (Term Sheet)',
    backupSource: 'Derived (Rate + 2%)',
    expectedValue: 'Percentage, e.g., 10.00%',
    fieldType: 'direct',
    dataType: 'Percent',
    section: 'loan-terms',
  },
  amortization: {
    fieldId: 'amortization',
    description: 'Amortization schedule.',
    primarySource: 'Document (Term Sheet)',
    backupSource: 'User Input',
    expectedValue: 'IO, 30yr, 25yr',
    fieldType: 'direct',
    dataType: 'Dropdown',
    section: 'loan-terms',
  },
  prepaymentTerms: {
    fieldId: 'prepaymentTerms',
    description: 'Prepayment terms and penalties.',
    primarySource: 'Document (Term Sheet)',
    backupSource: 'User Input',
    expectedValue: 'Text, e.g., "Minimum interest"',
    fieldType: 'direct',
    dataType: 'Text',
    section: 'loan-terms',
  },
  recourse: {
    fieldId: 'recourse',
    description: 'Recourse structure for the loan.',
    primarySource: 'Document (Term Sheet)',
    backupSource: 'User Input',
    expectedValue: 'Full, Partial, Non',
    fieldType: 'direct',
    dataType: 'Dropdown',
    section: 'loan-terms',
  },
  permTakeoutPlanned: {
    fieldId: 'permTakeoutPlanned',
    description: 'Whether permanent takeout financing is planned after construction.',
    primarySource: 'Document (Term Sheet)',
    backupSource: 'User Input',
    expectedValue: 'Yes/No (Boolean)',
    fieldType: 'direct',
    dataType: 'Boolean',
    section: 'loan-terms',
  },
  
  // Operating Expenses
  realEstateTaxes: {
    fieldId: 'realEstateTaxes',
    description: 'Annual real estate taxes.',
    primarySource: 'Document (Proforma)',
    backupSource: 'External (Tax Assessor)',
    expectedValue: 'Currency, e.g., $34,200',
    fieldType: 'direct',
    dataType: 'Currency',
    section: 'financial-details',
  },
  insurance: {
    fieldId: 'insurance',
    description: 'Annual property insurance costs.',
    primarySource: 'Document (Proforma)',
    backupSource: 'User Input',
    expectedValue: 'Currency, e.g., $92,800',
    fieldType: 'direct',
    dataType: 'Currency',
    section: 'financial-details',
  },
  utilitiesCosts: {
    fieldId: 'utilitiesCosts',
    description: 'Annual utility costs.',
    primarySource: 'Document (Proforma)',
    backupSource: 'User Input',
    expectedValue: 'Currency, e.g., $23,200',
    fieldType: 'direct',
    dataType: 'Currency',
    section: 'financial-details',
  },
  repairsAndMaintenance: {
    fieldId: 'repairsAndMaintenance',
    description: 'Annual repairs and maintenance budget.',
    primarySource: 'Document (Proforma)',
    backupSource: 'User Input',
    expectedValue: 'Currency, e.g., $46,400',
    fieldType: 'direct',
    dataType: 'Currency',
    section: 'financial-details',
  },
  managementFee: {
    fieldId: 'managementFee',
    description: 'Annual property management fee.',
    primarySource: 'Document (Proforma)',
    backupSource: 'Derived (3-5% EGI)',
    expectedValue: 'Currency, e.g., $85,000',
    fieldType: 'direct',
    dataType: 'Currency',
    section: 'financial-details',
  },
  generalAndAdmin: {
    fieldId: 'generalAndAdmin',
    description: 'Annual general and administrative expenses.',
    primarySource: 'Document (Proforma)',
    backupSource: 'User Input',
    expectedValue: 'Currency, e.g., $40,600',
    fieldType: 'direct',
    dataType: 'Currency',
    section: 'financial-details',
  },
  payroll: {
    fieldId: 'payroll',
    description: 'Annual payroll expenses.',
    primarySource: 'Document (Proforma)',
    backupSource: 'User Input',
    expectedValue: 'Currency, e.g., $174,000',
    fieldType: 'direct',
    dataType: 'Currency',
    section: 'financial-details',
  },
  reserves: {
    fieldId: 'reserves',
    description: 'Annual reserve contribution.',
    primarySource: 'Document (Proforma)',
    backupSource: 'Derived ($250/unit)',
    expectedValue: 'Currency, e.g., $23,200',
    fieldType: 'direct',
    dataType: 'Currency',
    section: 'financial-details',
  },
  
  // Investment Metrics
  noiYear1: {
    fieldId: 'noiYear1',
    description: 'Net Operating Income for Year 1. This is automatically calculated as EGI minus Total Expenses.',
    primarySource: 'Derived (EGI - Total Exp)',
    backupSource: 'Document (Proforma)',
    expectedValue: 'Currency, e.g., $2,268,000',
    fieldType: 'derived',
    dataType: 'Currency',
    section: 'financial-details',
  },
  yieldOnCost: {
    fieldId: 'yieldOnCost',
    description: 'Yield on cost percentage. This is automatically calculated as NOI divided by TDC.',
    primarySource: 'Derived (NOI / TDC)',
    backupSource: 'N/A',
    expectedValue: 'Percentage, e.g., 7.6%',
    fieldType: 'derived',
    dataType: 'Percent',
    section: 'financial-details',
  },
  capRate: {
    fieldId: 'capRate',
    description: 'Cap rate used for valuation.',
    primarySource: 'Document (Appraisal)',
    backupSource: 'External (CoStar)',
    expectedValue: 'Percentage, e.g., 5.50%',
    fieldType: 'direct',
    dataType: 'Percent',
    section: 'financial-details',
  },
  stabilizedValue: {
    fieldId: 'stabilizedValue',
    description: 'Stabilized property value. This is automatically calculated as NOI divided by Cap Rate.',
    primarySource: 'Derived (NOI / Cap Rate)',
    backupSource: 'Document (Appraisal)',
    expectedValue: 'Currency, e.g., $41,200,000',
    fieldType: 'derived',
    dataType: 'Currency',
    section: 'financial-details',
  },
  ltv: {
    fieldId: 'ltv',
    description: 'Loan-to-value ratio. This is automatically calculated as Loan divided by Value.',
    primarySource: 'Derived (Loan / Value)',
    backupSource: 'N/A',
    expectedValue: 'Percentage, e.g., 44%',
    fieldType: 'derived',
    dataType: 'Percent',
    section: 'financial-details',
  },
  debtYield: {
    fieldId: 'debtYield',
    description: 'Debt yield percentage. This is automatically calculated as NOI divided by Loan.',
    primarySource: 'Derived (NOI / Loan)',
    backupSource: 'N/A',
    expectedValue: 'Percentage, e.g., 12.6%',
    fieldType: 'derived',
    dataType: 'Percent',
    section: 'financial-details',
  },
  dscr: {
    fieldId: 'dscr',
    description: 'Debt service coverage ratio. This is automatically calculated as NOI divided by Debt Service.',
    primarySource: 'Derived (NOI / Debt Svc)',
    backupSource: 'N/A',
    expectedValue: 'Decimal, e.g., 1.25x',
    fieldType: 'derived',
    dataType: 'Decimal',
    section: 'financial-details',
  },
  
  // Legacy/Additional Financial Fields
  purchasePrice: {
    fieldId: 'purchasePrice',
    description: 'Purchase price for acquisition deals, or current basis for existing properties.',
    primarySource: 'Document (Purchase Agreement)',
    backupSource: 'User Input',
    expectedValue: 'Currency, e.g., $15,000,000',
    fieldType: 'direct',
    dataType: 'Currency',
    section: 'financials',
  },
  totalProjectCost: {
    fieldId: 'totalProjectCost',
    description: 'Total project cost including all hard and soft costs. For development projects, this is the same as Total Development Cost (TDC).',
    primarySource: 'Document (Dev Budget)',
    backupSource: 'User Input',
    expectedValue: 'Currency, e.g., $29,800,000',
    fieldType: 'direct',
    dataType: 'Currency',
    section: 'financials',
  },
  capexBudget: {
    fieldId: 'capexBudget',
    description: 'Capital expenditure budget for improvements, renovations, or value-add work.',
    primarySource: 'Document (Budget)',
    backupSource: 'User Input',
    expectedValue: 'Currency, e.g., $1,500,000',
    fieldType: 'direct',
    dataType: 'Currency',
    section: 'financials',
  },
  propertyNoiT12: {
    fieldId: 'propertyNoiT12',
    description: 'Net Operating Income for the trailing 12 months. Used for existing properties to show current performance.',
    primarySource: 'Document (Operating Statement)',
    backupSource: 'User Input',
    expectedValue: 'Currency, e.g., $450,000',
    fieldType: 'direct',
    dataType: 'Currency',
    section: 'financials',
  },
  stabilizedNoiProjected: {
    fieldId: 'stabilizedNoiProjected',
    description: 'Projected Net Operating Income at stabilization. This is the expected NOI once the property is fully leased and operating normally.',
    primarySource: 'Document (Proforma)',
    backupSource: 'User Input',
    expectedValue: 'Currency, e.g., $2,268,000',
    fieldType: 'direct',
    dataType: 'Currency',
    section: 'financials',
  },
  exitStrategy: {
    fieldId: 'exitStrategy',
    description: 'Planned exit strategy for the investment. This helps lenders understand your long-term plans.',
    primarySource: 'User Input',
    backupSource: 'N/A',
    expectedValue: 'Sale, Refinance, Long-Term Hold, Undecided',
    fieldType: 'direct',
    dataType: 'Dropdown',
    section: 'financials',
  },
  businessPlanSummary: {
    fieldId: 'businessPlanSummary',
    description: 'Summary of your business plan and strategy for the project. This should outline your approach to development, leasing, and operations.',
    primarySource: 'User Input',
    backupSource: 'N/A',
    expectedValue: 'Text description of business plan and strategy',
    fieldType: 'direct',
    dataType: 'Textarea',
    section: 'financials',
  },
  marketOverviewSummary: {
    fieldId: 'marketOverviewSummary',
    description: 'Overview of the market conditions, demographics, and trends that support the project.',
    primarySource: 'Document (Market Study)',
    backupSource: 'User Input',
    expectedValue: 'Text description of market conditions and trends',
    fieldType: 'direct',
    dataType: 'Textarea',
    section: 'financials',
  },
  equityCommittedPercent: {
    fieldId: 'equityCommittedPercent',
    description: 'Percentage of total equity that has been committed to the project.',
    primarySource: 'Document (Sources & Uses)',
    backupSource: 'User Input',
    expectedValue: 'Percentage, e.g., 100%',
    fieldType: 'direct',
    dataType: 'Percent',
    section: 'financials',
  },
  
  // Section 4: Market Context
  submarketName: {
    fieldId: 'submarketName',
    description: 'Name of the submarket where the property is located.',
    primarySource: 'Document (Market Study)',
    backupSource: 'External (CoStar)',
    expectedValue: 'e.g., Downtown Dallas',
    fieldType: 'direct',
    dataType: 'Text',
    section: 'market-context',
  },
  distanceToCBD: {
    fieldId: 'distanceToCBD',
    description: 'Distance to central business district. This is automatically calculated from geographic data.',
    primarySource: 'Derived (Geo-calc)',
    backupSource: 'External (Google Maps)',
    expectedValue: 'Decimal, e.g., 2.1 miles',
    fieldType: 'derived',
    dataType: 'Decimal',
    section: 'market-context',
  },
  distanceToEmployment: {
    fieldId: 'distanceToEmployment',
    description: 'Distance to major employment centers.',
    primarySource: 'Document (Market Study)',
    backupSource: 'External (Google Maps)',
    expectedValue: 'Text, e.g., "2.1 miles"',
    fieldType: 'direct',
    dataType: 'Text',
    section: 'market-context',
  },
  distanceToTransit: {
    fieldId: 'distanceToTransit',
    description: 'Distance to public transit. This is automatically calculated from geographic data.',
    primarySource: 'Derived (Geo-calc)',
    backupSource: 'External (Walk Score)',
    expectedValue: 'Decimal, e.g., 0.5 miles',
    fieldType: 'derived',
    dataType: 'Decimal',
    section: 'market-context',
  },
  walkabilityScore: {
    fieldId: 'walkabilityScore',
    description: 'Walk Score for the property location.',
    primarySource: 'Document (Market Study)',
    backupSource: 'External (Walk Score)',
    expectedValue: 'Integer, 0-100, e.g., 85',
    fieldType: 'direct',
    dataType: 'Integer',
    section: 'market-context',
  },
  population3Mi: {
    fieldId: 'population3Mi',
    description: 'Population within 3 miles of the property.',
    primarySource: 'External (Census ACS)',
    backupSource: 'Document (Market Study)',
    expectedValue: 'Integer, e.g., 174,270',
    fieldType: 'direct',
    dataType: 'Integer',
    section: 'market-context',
  },
  popGrowth201020: {
    fieldId: 'popGrowth201020',
    description: 'Population growth from 2010-2020.',
    primarySource: 'External (Census ACS)',
    backupSource: 'Document (Market Study)',
    expectedValue: 'Percentage, e.g., 23.3%',
    fieldType: 'direct',
    dataType: 'Percent',
    section: 'market-context',
  },
  projGrowth202429: {
    fieldId: 'projGrowth202429',
    description: 'Projected population growth from 2024-2029.',
    primarySource: 'External (Census ACS)',
    backupSource: 'Document (Market Study)',
    expectedValue: 'Percentage, e.g., 6.9%',
    fieldType: 'direct',
    dataType: 'Percent',
    section: 'market-context',
  },
  medianHHIncome: {
    fieldId: 'medianHHIncome',
    description: 'Median household income within 3 miles.',
    primarySource: 'External (Census ACS)',
    backupSource: 'Document (Market Study)',
    expectedValue: 'Currency, e.g., $85,906',
    fieldType: 'direct',
    dataType: 'Currency',
    section: 'market-context',
  },
  renterOccupiedPercent: {
    fieldId: 'renterOccupiedPercent',
    description: 'Percentage of households that are renter-occupied within 3 miles.',
    primarySource: 'External (Census ACS)',
    backupSource: 'Document (Market Study)',
    expectedValue: 'Percentage, e.g., 76.7%',
    fieldType: 'direct',
    dataType: 'Percent',
    section: 'market-context',
  },
  bachelorsDegreePercent: {
    fieldId: 'bachelorsDegreePercent',
    description: 'Percentage of population with bachelor\'s degree within 3 miles.',
    primarySource: 'External (Census ACS)',
    backupSource: 'Document (Market Study)',
    expectedValue: 'Percentage, e.g., 50.2%',
    fieldType: 'direct',
    dataType: 'Percent',
    section: 'market-context',
  },
  
  // Section 5: Special Considerations
  opportunityZone: {
    fieldId: 'opportunityZone',
    description: 'Whether the property is located in an Opportunity Zone.',
    primarySource: 'External (US Treasury)',
    backupSource: 'User Input',
    expectedValue: 'Yes/No (Boolean)',
    fieldType: 'direct',
    dataType: 'Boolean',
    section: 'special-considerations',
  },
  affordableHousing: {
    fieldId: 'affordableHousing',
    description: 'Whether the project includes affordable housing units.',
    primarySource: 'Document (Reg Agreement)',
    backupSource: 'User Input',
    expectedValue: 'Yes/No (Boolean)',
    fieldType: 'direct',
    dataType: 'Boolean',
    section: 'special-considerations',
  },
  affordableUnitsNumber: {
    fieldId: 'affordableUnitsNumber',
    description: 'Number of affordable housing units.',
    primarySource: 'Document (Reg Agreement)',
    backupSource: 'User Input',
    expectedValue: 'Integer, e.g., 58',
    fieldType: 'direct',
    dataType: 'Integer',
    section: 'special-considerations',
  },
  amiTargetPercent: {
    fieldId: 'amiTargetPercent',
    description: 'Area Median Income (AMI) target percentage for affordable units.',
    primarySource: 'Document (Reg Agreement)',
    backupSource: 'User Input',
    expectedValue: 'Percentage, e.g., 80% AMI',
    fieldType: 'direct',
    dataType: 'Percent',
    section: 'special-considerations',
  },
  taxExemption: {
    fieldId: 'taxExemption',
    description: 'Whether the project has tax exemption status.',
    primarySource: 'Document (Incentive Agmt)',
    backupSource: 'User Input',
    expectedValue: 'Yes/No (Boolean)',
    fieldType: 'direct',
    dataType: 'Boolean',
    section: 'special-considerations',
  },
  tifDistrict: {
    fieldId: 'tifDistrict',
    description: 'Whether the property is in a TIF (Tax Increment Financing) district.',
    primarySource: 'External (City GIS)',
    backupSource: 'User Input',
    expectedValue: 'Yes/No (Boolean)',
    fieldType: 'direct',
    dataType: 'Boolean',
    section: 'special-considerations',
  },
  taxAbatement: {
    fieldId: 'taxAbatement',
    description: 'Whether the project has tax abatement benefits.',
    primarySource: 'Document (Incentive Agmt)',
    backupSource: 'User Input',
    expectedValue: 'Yes/No (Boolean)',
    fieldType: 'direct',
    dataType: 'Boolean',
    section: 'special-considerations',
  },
  paceFinancing: {
    fieldId: 'paceFinancing',
    description: 'Whether PACE (Property Assessed Clean Energy) financing is used.',
    primarySource: 'User Input',
    backupSource: 'N/A',
    expectedValue: 'Yes/No (Boolean)',
    fieldType: 'direct',
    dataType: 'Boolean',
    section: 'special-considerations',
  },
  historicTaxCredits: {
    fieldId: 'historicTaxCredits',
    description: 'Whether historic tax credits are being utilized.',
    primarySource: 'Document (NPS Cert)',
    backupSource: 'User Input',
    expectedValue: 'Yes/No (Boolean)',
    fieldType: 'direct',
    dataType: 'Boolean',
    section: 'special-considerations',
  },
  newMarketsCredits: {
    fieldId: 'newMarketsCredits',
    description: 'Whether New Markets Tax Credits are being utilized.',
    primarySource: 'External (CDFI Fund)',
    backupSource: 'User Input',
    expectedValue: 'Yes/No (Boolean)',
    fieldType: 'direct',
    dataType: 'Boolean',
    section: 'special-considerations',
  },
  
  // Section 6: Timeline & Milestones
  landAcqClose: {
    fieldId: 'landAcqClose',
    description: 'Land acquisition closing date.',
    primarySource: 'Document (Settlement Stmt)',
    backupSource: 'User Input',
    expectedValue: 'Date',
    fieldType: 'direct',
    dataType: 'Date',
    section: 'timeline',
  },
  entitlements: {
    fieldId: 'entitlements',
    description: 'Entitlement approval status.',
    primarySource: 'Document (Zoning Letter)',
    backupSource: 'User Input',
    expectedValue: 'Approved/Pending',
    fieldType: 'direct',
    dataType: 'Dropdown',
    section: 'timeline',
  },
  finalPlans: {
    fieldId: 'finalPlans',
    description: 'Final plans approval status.',
    primarySource: 'Document (Arch Contract)',
    backupSource: 'User Input',
    expectedValue: 'Approved/Pending',
    fieldType: 'direct',
    dataType: 'Dropdown',
    section: 'timeline',
  },
  permitsIssued: {
    fieldId: 'permitsIssued',
    description: 'Building permits issuance status.',
    primarySource: 'Document (Building Permits)',
    backupSource: 'External (Census BPS)',
    expectedValue: 'Issued/Pending',
    fieldType: 'direct',
    dataType: 'Dropdown',
    section: 'timeline',
  },
  verticalStart: {
    fieldId: 'verticalStart',
    description: 'Date for vertical construction start.',
    primarySource: 'Document (Schedule)',
    backupSource: 'User Input',
    expectedValue: 'Date',
    fieldType: 'direct',
    dataType: 'Date',
    section: 'timeline',
  },
  firstOccupancy: {
    fieldId: 'firstOccupancy',
    description: 'First occupancy date.',
    primarySource: 'Document (Schedule)',
    backupSource: 'User Input',
    expectedValue: 'Date',
    fieldType: 'direct',
    dataType: 'Date',
    section: 'timeline',
  },
  stabilization: {
    fieldId: 'stabilization',
    description: 'Projected stabilization date.',
    primarySource: 'Document (Proforma)',
    backupSource: 'User Input',
    expectedValue: 'Date',
    fieldType: 'direct',
    dataType: 'Date',
    section: 'timeline',
  },
  preLeasedSF: {
    fieldId: 'preLeasedSF',
    description: 'Pre-leased square footage.',
    primarySource: 'Document (Lease Agmt)',
    backupSource: 'User Input',
    expectedValue: 'Integer, e.g., 30,000',
    fieldType: 'direct',
    dataType: 'Integer',
    section: 'timeline',
  },
  
  // Section 7: Site & Context
  totalSiteAcreage: {
    fieldId: 'totalSiteAcreage',
    description: 'Total site acreage.',
    primarySource: 'Document (ALTA Survey)',
    backupSource: 'External (Regrid API)',
    expectedValue: 'Decimal, e.g., 2.5 acres',
    fieldType: 'direct',
    dataType: 'Decimal',
    section: 'site-context',
  },
  currentSiteStatus: {
    fieldId: 'currentSiteStatus',
    description: 'Current status of the site.',
    primarySource: 'Document (Phase I ESA)',
    backupSource: 'External (Street View)',
    expectedValue: 'Vacant/Existing',
    fieldType: 'direct',
    dataType: 'Dropdown',
    section: 'site-context',
  },
  topography: {
    fieldId: 'topography',
    description: 'Site topography.',
    primarySource: 'Document (Survey)',
    backupSource: 'External (USGS API)',
    expectedValue: 'Flat/Sloped',
    fieldType: 'direct',
    dataType: 'Dropdown',
    section: 'site-context',
  },
  environmental: {
    fieldId: 'environmental',
    description: 'Environmental status of the site.',
    primarySource: 'Document (Phase I ESA)',
    backupSource: 'External (EPA API)',
    expectedValue: 'Clean/Remediation',
    fieldType: 'direct',
    dataType: 'Dropdown',
    section: 'site-context',
  },
  utilities: {
    fieldId: 'utilities',
    description: 'Utility availability on site.',
    primarySource: 'Document (Civil Plans)',
    backupSource: 'User Input',
    expectedValue: 'Available/None',
    fieldType: 'direct',
    dataType: 'Dropdown',
    section: 'site-context',
  },
  siteAccess: {
    fieldId: 'siteAccess',
    description: 'Site access points and streets.',
    primarySource: 'Document (Civil Plans)',
    backupSource: 'External (Google Maps)',
    expectedValue: 'Text, e.g., "Hickory St, Ferris St"',
    fieldType: 'direct',
    dataType: 'Text',
    section: 'site-context',
  },
  proximityShopping: {
    fieldId: 'proximityShopping',
    description: 'Nearby shopping areas and retail.',
    primarySource: 'Document (Market Study)',
    backupSource: 'External (Google Maps)',
    expectedValue: 'Text, e.g., "Farmers Market, Deep Ellum nearby"',
    fieldType: 'direct',
    dataType: 'Text',
    section: 'site-context',
  },
  proximityRestaurants: {
    fieldId: 'proximityRestaurants',
    description: 'Nearby restaurants and dining.',
    primarySource: 'Document (Market Study)',
    backupSource: 'External (Google Maps)',
    expectedValue: 'Text',
    fieldType: 'direct',
    dataType: 'Text',
    section: 'site-context',
  },
  proximityParks: {
    fieldId: 'proximityParks',
    description: 'Nearby parks and recreational areas.',
    primarySource: 'Document (Market Study)',
    backupSource: 'External (Google Maps)',
    expectedValue: 'Text',
    fieldType: 'direct',
    dataType: 'Text',
    section: 'site-context',
  },
  proximitySchools: {
    fieldId: 'proximitySchools',
    description: 'Nearby schools and educational institutions.',
    primarySource: 'Document (Market Study)',
    backupSource: 'External (Google Maps)',
    expectedValue: 'Text',
    fieldType: 'direct',
    dataType: 'Text',
    section: 'site-context',
  },
  proximityHospitals: {
    fieldId: 'proximityHospitals',
    description: 'Nearby hospitals and healthcare facilities.',
    primarySource: 'Document (Market Study)',
    backupSource: 'External (Google Maps)',
    expectedValue: 'Text',
    fieldType: 'direct',
    dataType: 'Text',
    section: 'site-context',
  },
  
  // Section 8: Sponsor Information
  sponsorEntityName: {
    fieldId: 'sponsorEntityName',
    description: 'Name of the sponsor/borrower entity.',
    primarySource: 'Document (Org Chart)',
    backupSource: 'User Input',
    expectedValue: 'e.g., Hoque Global',
    fieldType: 'direct',
    dataType: 'Text',
    section: 'sponsor-info',
  },
  sponsorStructure: {
    fieldId: 'sponsorStructure',
    description: 'Legal structure of the sponsor entity.',
    primarySource: 'Document (Org Chart)',
    backupSource: 'User Input',
    expectedValue: 'Text, e.g., "General Partner"',
    fieldType: 'direct',
    dataType: 'Text',
    section: 'sponsor-info',
  },
  equityPartner: {
    fieldId: 'equityPartner',
    description: 'Equity partner or investor name.',
    primarySource: 'Document (Org Chart)',
    backupSource: 'User Input',
    expectedValue: 'e.g., ACARA',
    fieldType: 'direct',
    dataType: 'Text',
    section: 'sponsor-info',
  },
  contactInfo: {
    fieldId: 'contactInfo',
    description: 'Primary contact information for the project.',
    primarySource: 'User Input',
    backupSource: 'N/A',
    expectedValue: 'Text, e.g., "Cody Field (415.202.3258), Joel Heikenfeld (972.455.1943)"',
    fieldType: 'direct',
    dataType: 'Text',
    section: 'sponsor-info',
  },
};

/**
 * Get metadata for a specific field
 */
export const getFieldMetadata = (fieldId: string): FieldMetadata | undefined => {
  return projectResumeFieldMetadata[fieldId];
};

/**
 * Get all fields for a specific section
 */
export const getFieldsForSection = (section: string): FieldMetadata[] => {
  return Object.values(projectResumeFieldMetadata).filter(
    (field) => field.section === section
  );
};

