// src/lib/project-resume-field-metadata.ts
// Field metadata configuration for Project Resume fields based on Hoque_Data.md

export interface FieldMetadata {
	fieldId: string;
	description: string;
	expectedValue: string;
	dataType?: string;
	section: string;
}

export const projectResumeFieldMetadata: Record<string, FieldMetadata> = {
	// Section 1: Project Identification & Basic Info
	projectName: {
		fieldId: "projectName",
		description:
			"The official name of your project. Used for identification in the dashboard and marketing materials.",
		expectedValue: "e.g., SoGood Apartments",
		dataType: "Text",
		section: "basic-info",
	},
	propertyAddressStreet: {
		fieldId: "propertyAddressStreet",
		description:
			"The street address of the property. Selection triggers auto-population of city, state, and zip.",
		expectedValue: "e.g., 2300 Hickory St",
		dataType: "Address",
		section: "basic-info",
	},
	propertyAddressCity: {
		fieldId: "propertyAddressCity",
		description:
			"City where the property is located. Auto-populated from the address selection.",
		expectedValue: "e.g., Dallas",
		dataType: "Text",
		section: "basic-info",
	},
	propertyAddressState: {
		fieldId: "propertyAddressState",
		description:
			"State where the property is located. Auto-populated from the address selection.",
		expectedValue: "2-letter state code, e.g., TX",
		dataType: "Dropdown",
		section: "basic-info",
	},
	propertyAddressZip: {
		fieldId: "propertyAddressZip",
		description:
			"ZIP code of the property location. Auto-populated from the address selection.",
		expectedValue: "e.g., 75215",
		dataType: "Numeric",
		section: "basic-info",
	},
	propertyAddressCounty: {
		fieldId: "propertyAddressCounty",
		description:
			"County where the property is located. Used for tax jurisdiction determination.",
		expectedValue: "e.g., Dallas County",
		dataType: "Text",
		section: "basic-info",
	},
	parcelNumber: {
		fieldId: "parcelNumber",
		description:
			"Legal property identifier(s). Comma-separated if multiple parcels.",
		expectedValue: "e.g., 000472000A01B0100",
		dataType: "Text",
		section: "basic-info",
	},
	zoningDesignation: {
		fieldId: "zoningDesignation",
		description:
			"Zoning designation determining development rights (e.g., density, height, use).",
		expectedValue: "e.g., PD317",
		dataType: "Text",
		section: "basic-info",
	},
	assetType: {
		fieldId: "assetType",
		description:
			"Primary asset type classification. Matches project with appropriate lenders.",
		expectedValue:
			"Multifamily, Office, Retail, Industrial, Mixed-Use, etc.",
		dataType: "Dropdown",
		section: "basic-info",
	},
	projectPhase: {
		fieldId: "projectPhase",
		description:
			"Current phase of the project life cycle. Determines available financing types.",
		expectedValue:
			"Acquisition, Refinance, Construction, Bridge, Development, Value-Add, Other",
		dataType: "Dropdown",
		section: "basic-info",
	},
	projectDescription: {
		fieldId: "projectDescription",
		description:
			"Brief narrative of the project, location, and key features for lender review.",
		expectedValue:
			'Text description, e.g., "Ground-up development of Building B within the SoGood master plan..."',
		dataType: "Textarea",
		section: "basic-info",
	},
	constructionType: {
		fieldId: "constructionType",
		description:
			"Type of construction work involved. Affects risk profile and loan sizing.",
		expectedValue: "Ground-Up, Renovation, Adaptive Reuse",
		dataType: "Radio",
		section: "basic-info",
	},
	groundbreakingDate: {
		fieldId: "groundbreakingDate",
		description: "Planned date for construction start.",
		expectedValue: "Date, e.g., Q3 2025",
		dataType: "Date",
		section: "basic-info",
	},
	completionDate: {
		fieldId: "completionDate",
		description: "Expected project completion / CO date.",
		expectedValue: "Date, e.g., Q3 2027",
		dataType: "Date",
		section: "basic-info",
	},
	totalDevelopmentCost: {
		fieldId: "totalDevelopmentCost",
		description:
			"Total development cost (TDC). Sum of all budget line items.",
		expectedValue: "Currency, e.g., $29,800,000",
		dataType: "Currency",
		section: "basic-info",
	},
	dealStatus: {
		fieldId: "dealStatus",
		description:
			"Current workflow status of the deal (e.g. actively underwriting vs. closed).",
		expectedValue:
			"Inquiry, Underwriting, Pre-Submission, Submitted, Closed",
		dataType: "Dropdown",
		section: "basic-info",
	},
	expectedZoningChanges: {
		fieldId: "expectedZoningChanges",
		description: "Any zoning changes required for the project.",
		expectedValue: "None, Variance, PUD, Re-Zoning",
		dataType: "Dropdown",
		section: "basic-info",
	},
	expectedHoldPeriod: {
		fieldId: "expectedHoldPeriod",
		description: "Anticipated holding period for the asset in years.",
		expectedValue: "Integer, e.g., 5",
		dataType: "Integer",
		section: "basic-info",
	},
	syndicationStatus: {
		fieldId: "syndicationStatus",
		description: "Status of equity syndication or capital raising.",
		expectedValue: "Committed, In Process, TBD",
		dataType: "Dropdown",
		section: "basic-info",
	},
	sponsorExperience: {
		fieldId: "sponsorExperience",
		description: "Sponsor's level of experience with similar projects.",
		expectedValue: "First-Time, Emerging (1-3), Seasoned (3+)",
		dataType: "Dropdown",
		section: "basic-info",
	},
	ltvStressMax: {
		fieldId: "ltvStressMax",
		description: "Maximum LTV if Cap Rate expands +50bps.",
		expectedValue: "Percentage, e.g., 50%",
		dataType: "Percent",
		section: "basic-info",
	},
	dscrStressMin: {
		fieldId: "dscrStressMin",
		description: "Minimum DSCR if Vacancy increases 5%.",
		expectedValue: "Decimal, e.g., 1.10",
		dataType: "Decimal",
		section: "basic-info",
	},
	loanAmountRequested: {
		fieldId: "loanAmountRequested",
		description: "Total loan amount requested from the lender.",
		expectedValue: "Currency, e.g., $18,000,000",
		dataType: "Currency",
		section: "loan-info",
	},
	loanType: {
		fieldId: "loanType",
		description: "Specific type of loan product being requested.",
		expectedValue:
			"Senior Debt, Mezzanine, Preferred Equity, Common Equity, JV Equity, Other",
		dataType: "Dropdown",
		section: "loan-info",
	},
	requestedTerm: {
		fieldId: "requestedTerm",
		description: "Requested loan term in years.",
		expectedValue: "Number of years, e.g., 5",
		dataType: "Integer",
		section: "loan-terms",
	},
	targetLtvPercent: {
		fieldId: "targetLtvPercent",
		description: "Target Loan-to-Value ratio (Loan / Stabilized Value).",
		expectedValue: "Percentage, e.g., 70%",
		dataType: "Percent",
		section: "loan-info",
	},
	targetLtcPercent: {
		fieldId: "targetLtcPercent",
		description: "Target Loan-to-Cost ratio (Loan / Total Development Cost).",
		expectedValue: "Percentage, e.g., 80%",
		dataType: "Percent",
		section: "loan-info",
	},
	amortizationYears: {
		fieldId: "amortizationYears",
		description: "Amortization schedule in years (e.g. 30 years).",
		expectedValue: "Number of years, e.g., 30",
		dataType: "Integer",
		section: "loan-info",
	},
	interestOnlyPeriodMonths: {
		fieldId: "interestOnlyPeriodMonths",
		description: "Interest-only period in months.",
		expectedValue: "Number of months, e.g., 36",
		dataType: "Integer",
		section: "loan-info",
	},
	interestRateType: {
		fieldId: "interestRateType",
		description: "Fixed vs Floating interest rate.",
		expectedValue: "Fixed, Floating, Not Specified",
		dataType: "Dropdown",
		section: "loan-info",
	},
	targetCloseDate: {
		fieldId: "targetCloseDate",
		description: "Target date for closing the loan.",
		expectedValue: "Date, e.g., 2025-08-15",
		dataType: "Date",
		section: "loan-info",
	},
	recoursePreference: {
		fieldId: "recoursePreference",
		description:
			"Preferred recourse structure (Full, Limited, Non-Recourse).",
		expectedValue:
			"Full Recourse, Partial Recourse, Non-Recourse, Flexible",
		dataType: "Dropdown",
		section: "loan-info",
	},
	useOfProceeds: {
		fieldId: "useOfProceeds",
		description: "Breakdown of how loan proceeds will be utilized.",
		expectedValue:
			'Text description, e.g., "Land acquisition, vertical construction, soft costs..."',
		dataType: "Textarea",
		section: "loan-info",
	},

	// Section 2: Property Specifications
	totalResidentialUnits: {
		fieldId: "totalResidentialUnits",
		description:
			"Total number of residential units. Automatically summed from unit mix.",
		expectedValue: "Integer, e.g., 116",
		dataType: "Integer",
		section: "property-specs",
	},
	totalResidentialNRSF: {
		fieldId: "totalResidentialNRSF",
		description:
			"Total Net Rentable Square Feet (NRSF) for residential component.",
		expectedValue: "Integer, e.g., 59,520",
		dataType: "Integer",
		section: "property-specs",
	},
	averageUnitSize: {
		fieldId: "averageUnitSize",
		description: "Average size per unit (NRSF / Total Units).",
		expectedValue: "Integer, e.g., 513 SF",
		dataType: "Integer",
		section: "property-specs",
	},
	totalCommercialGRSF: {
		fieldId: "totalCommercialGRSF",
		description:
			"Total Gross Rentable Square Feet for commercial space, derived from commercialSpaceMix.",
		expectedValue: "Integer, e.g., 49,569",
		dataType: "Integer",
		section: "property-specs",
	},
	grossBuildingArea: {
		fieldId: "grossBuildingArea",
		description: "Total Gross Building Area (GBA) including common areas.",
		expectedValue: "Integer, e.g., 127,406",
		dataType: "Integer",
		section: "property-specs",
	},
	numberOfStories: {
		fieldId: "numberOfStories",
		description: "Number of stories above grade.",
		expectedValue: "Integer, e.g., 6",
		dataType: "Integer",
		section: "property-specs",
	},
	buildingType: {
		fieldId: "buildingType",
		description: "Structural building type classification.",
		expectedValue: "High-rise, Mid-rise, Garden, Podium",
		dataType: "Dropdown",
		section: "property-specs",
	},
	parkingSpaces: {
		fieldId: "parkingSpaces",
		description: "Total number of parking spaces provided.",
		expectedValue: "Integer, e.g., 180",
		dataType: "Integer",
		section: "property-specs",
	},
	parkingRatio: {
		fieldId: "parkingRatio",
		description: "Parking spaces per unit (Spaces / Units).",
		expectedValue: "Decimal, e.g., 1.55",
		dataType: "Decimal",
		section: "property-specs",
	},
	parkingType: {
		fieldId: "parkingType",
		description: "Configuration of parking (Surface, Garage, etc.).",
		expectedValue: "Surface, Structured, Underground (checkbox)",
		dataType: "Checkbox",
		section: "property-specs",
	},
	amenityList: {
		fieldId: "amenityList",
		description: "Key amenities available to tenants.",
		expectedValue: "Pool, Gym, Coworking, etc. (multi-select)",
		dataType: "Checklist",
		section: "property-specs",
	},
	amenitySF: {
		fieldId: "amenitySF",
		description: "Total square footage allocated to amenities.",
		expectedValue: "Integer, e.g., 35,264 SF",
		dataType: "Integer",
		section: "property-specs",
	},
	buildingEfficiency: {
		fieldId: "buildingEfficiency",
		description: "Efficiency ratio (NRSF / GBA). Target >80%.",
		expectedValue: "Percentage, e.g., 82%",
		dataType: "Percent",
		section: "property-specs",
	},
	studioCount: {
		fieldId: "studioCount",
		description: "Number of studio units derived from residentialUnitMix.",
		expectedValue: "Integer, e.g., 12",
		dataType: "Integer",
		section: "property-specs",
	},
	oneBedCount: {
		fieldId: "oneBedCount",
		description: "Number of 1-bedroom units derived from residentialUnitMix.",
		expectedValue: "Integer, e.g., 46",
		dataType: "Integer",
		section: "property-specs",
	},
	twoBedCount: {
		fieldId: "twoBedCount",
		description: "Number of 2-bedroom units derived from residentialUnitMix.",
		expectedValue: "Integer, e.g., 58",
		dataType: "Integer",
		section: "property-specs",
	},
	threeBedCount: {
		fieldId: "threeBedCount",
		description: "Number of 3-bedroom units derived from residentialUnitMix.",
		expectedValue: "Integer, e.g., 0",
		dataType: "Integer",
		section: "property-specs",
	},
	furnishedUnits: {
		fieldId: "furnishedUnits",
		description: "Whether units are offered furnished.",
		expectedValue: "Yes/No (Boolean)",
		dataType: "Boolean",
		section: "property-specs",
	},
	lossToLease: {
		fieldId: "lossToLease",
		description: "Loss to lease percentage (Market Rent vs Actual Rent).",
		expectedValue: "Percentage, e.g., 5%",
		dataType: "Percent",
		section: "property-specs",
	},
	adaCompliantPercent: {
		fieldId: "adaCompliantPercent",
		description:
			"Percentage of units compliant with ADA. (Min 5% for some programs).",
		expectedValue: "Percentage, e.g., 5%",
		dataType: "Percent",
		section: "property-specs",
	},
	hvacSystem: {
		fieldId: "hvacSystem",
		description: "HVAC system type used in the building.",
		expectedValue: "Central, Split System, PTAC, VRF",
		dataType: "Dropdown",
		section: "property-specs",
	},
	roofTypeAge: {
		fieldId: "roofTypeAge",
		description: "Roof material type and age.",
		expectedValue: 'Text, e.g., "TPO, 2 years old"',
		dataType: "Text",
		section: "property-specs",
	},
	solarCapacity: {
		fieldId: "solarCapacity",
		description: "Solar energy capacity in kW.",
		expectedValue: "Numeric, e.g., 100 kW",
		dataType: "Numeric",
		section: "property-specs",
	},
	evChargingStations: {
		fieldId: "evChargingStations",
		description: "Number of electric vehicle charging stations.",
		expectedValue: "Integer, e.g., 8",
		dataType: "Integer",
		section: "property-specs",
	},
	leedGreenRating: {
		fieldId: "leedGreenRating",
		description: "Sustainability certification level (LEED, NGBS).",
		expectedValue: "Certified, Silver, Gold, Platinum, NGBS",
		dataType: "Dropdown",
		section: "property-specs",
	},
	targetMarket: {
		fieldId: "targetMarket",
		description: "Target market demographic for the property.",
		expectedValue: "Young Professionals, Families, Seniors, Students, etc.",
		dataType: "Text",
		section: "property-specs",
	},
	avgRentPSF: {
		fieldId: "avgRentPSF",
		description: "Average rent per square foot calculated from unit mix.",
		expectedValue: "Currency, e.g., $2.50/SF",
		dataType: "Currency",
		section: "property-specs",
	},
	luxuryTier: {
		fieldId: "luxuryTier",
		description: "Luxury tier classification based on rent PSF.",
		expectedValue: "Luxury, Premium, Value, Economy",
		dataType: "Dropdown",
		section: "property-specs",
	},
	competitivePosition: {
		fieldId: "competitivePosition",
		description: "Competitive position relative to rent comps.",
		expectedValue: "Top 20%, Middle 60%, Bottom 20%",
		dataType: "Dropdown",
		section: "property-specs",
	},

	// Section 3: Financial Details
	landAcquisition: {
		fieldId: "landAcquisition",
		description: "Cost to acquire the land.",
		expectedValue: "Currency, e.g., $6,000,000",
		dataType: "Currency",
		section: "financial-details",
	},
	baseConstruction: {
		fieldId: "baseConstruction",
		description: "Hard construction costs.",
		expectedValue: "Currency, e.g., $16,950,000",
		dataType: "Currency",
		section: "financial-details",
	},
	contingency: {
		fieldId: "contingency",
		description: "Budget buffer for cost overruns.",
		expectedValue: "Currency, e.g., $847,500",
		dataType: "Currency",
		section: "financial-details",
	},
	ffe: {
		fieldId: "ffe",
		description: "Furniture, Fixtures & Equipment costs.",
		expectedValue: "Currency, e.g., $580,000",
		dataType: "Currency",
		section: "financial-details",
	},
	constructionFees: {
		fieldId: "constructionFees",
		description: "General Contractor fees/General Conditions.",
		expectedValue: "Currency, e.g., $174,000",
		dataType: "Currency",
		section: "financial-details",
	},
	aeFees: {
		fieldId: "aeFees",
		description: "Architecture and Engineering fees.",
		expectedValue: "Currency, e.g., $859,800",
		dataType: "Currency",
		section: "financial-details",
	},
	thirdPartyReports: {
		fieldId: "thirdPartyReports",
		description: "Costs for appraisal, environmental, etc.",
		expectedValue: "Currency, e.g., $50,000",
		dataType: "Currency",
		section: "financial-details",
	},
	legalAndOrg: {
		fieldId: "legalAndOrg",
		description: "Legal and organizational formation costs.",
		expectedValue: "Currency, e.g., $50,000",
		dataType: "Currency",
		section: "financial-details",
	},
	titleAndRecording: {
		fieldId: "titleAndRecording",
		description: "Title insurance and recording fees.",
		expectedValue: "Currency, e.g., $75,000",
		dataType: "Currency",
		section: "financial-details",
	},
	taxesDuringConstruction: {
		fieldId: "taxesDuringConstruction",
		description: "Property taxes payable during construction period.",
		expectedValue: "Currency, e.g., $20,000",
		dataType: "Currency",
		section: "financial-details",
	},
	workingCapital: {
		fieldId: "workingCapital",
		description: "Operating reserve for construction period.",
		expectedValue: "Currency, e.g., $1,900,000",
		dataType: "Currency",
		section: "financial-details",
	},
	developerFee: {
		fieldId: "developerFee",
		description: "Developer fee amount.",
		expectedValue: "Currency, e.g., $678,000",
		dataType: "Currency",
		section: "financial-details",
	},
	pfcStructuringFee: {
		fieldId: "pfcStructuringFee",
		description: "Fee for structuring PFC/Tax Exemption.",
		expectedValue: "Currency, e.g., $116,000",
		dataType: "Currency",
		section: "financial-details",
	},
	enviroRemediation: {
		fieldId: "enviroRemediation",
		description: "Environmental remediation costs for site cleanup.",
		expectedValue: "Currency, e.g., $500,000",
		dataType: "Currency",
		section: "financial-details",
	},
	relocationCosts: {
		fieldId: "relocationCosts",
		description: "Costs associated with relocating existing tenants or occupants.",
		expectedValue: "Currency, e.g., $200,000",
		dataType: "Currency",
		section: "financial-details",
	},
	syndicationCosts: {
		fieldId: "syndicationCosts",
		description: "Costs related to syndicating equity or raising capital.",
		expectedValue: "Currency, e.g., $150,000",
		dataType: "Currency",
		section: "financial-details",
	},
	loanFees: {
		fieldId: "loanFees",
		description: "Origination and other loan fees.",
		expectedValue: "Currency, e.g., $360,000",
		dataType: "Currency",
		section: "financial-details",
	},
	interestReserve: {
		fieldId: "interestReserve",
		description: "Reserve to pay interest during construction.",
		expectedValue: "Currency, e.g., $1,147,500",
		dataType: "Currency",
		section: "financial-details",
	},

	sponsorEquity: {
		fieldId: "sponsorEquity",
		description: "Equity contributed by the sponsor.",
		expectedValue: "Currency, e.g., $11,800,000",
		dataType: "Currency",
		section: "financial-details",
	},
	interestRate: {
		fieldId: "interestRate",
		description: "Loan interest rate.",
		expectedValue: "Percentage, e.g., 8.00%",
		dataType: "Percent",
		section: "loan-terms",
	},
	underwritingRate: {
		fieldId: "underwritingRate",
		description: "Stressed interest rate used for underwriting.",
		expectedValue: "Percentage, e.g., 10.00%",
		dataType: "Percent",
		section: "loan-terms",
	},

	prepaymentTerms: {
		fieldId: "prepaymentTerms",
		description: "Terms governing loan prepayment penalties.",
		expectedValue: 'Text, e.g., "Minimum interest"',
		dataType: "Text",
		section: "loan-terms",
	},
	prepaymentPremium: {
		fieldId: "prepaymentPremium",
		description: "Premium or penalty for prepaying the loan early.",
		expectedValue: "Currency or percentage, e.g., $100,000 or 2%",
		dataType: "Currency",
		section: "loan-terms",
	},
	permTakeoutPlanned: {
		fieldId: "permTakeoutPlanned",
		description: "Is permanent financing takeout planned?",
		expectedValue: "Yes/No (Boolean)",
		dataType: "Boolean",
		section: "loan-terms",
	},
	allInRate: {
		fieldId: "allInRate",
		description: "All-in interest rate including spreads and fees.",
		expectedValue: "Percentage, e.g., 7.2%",
		dataType: "Percent",
		section: "loan-terms",
	},
	taxCreditEquity: {
		fieldId: "taxCreditEquity",
		description: "Equity from tax credits (LIHTC, HTC, etc.).",
		expectedValue: "Currency, e.g., $0",
		dataType: "Currency",
		section: "financial-details",
	},
	gapFinancing: {
		fieldId: "gapFinancing",
		description: "Additional gap funding sources (TIF, grants).",
		expectedValue: "Currency, e.g., $0",
		dataType: "Currency",
		section: "financial-details",
	},

	// Operating Expenses
	realEstateTaxes: {
		fieldId: "realEstateTaxes",
		description: "Projected annual real estate taxes.",
		expectedValue: "Currency, e.g., $34,200",
		dataType: "Currency",
		section: "financial-details",
	},
	insurance: {
		fieldId: "insurance",
		description: "Projected annual insurance premium.",
		expectedValue: "Currency, e.g., $92,800",
		dataType: "Currency",
		section: "financial-details",
	},
	utilitiesCosts: {
		fieldId: "utilitiesCosts",
		description: "Projected annual utility costs.",
		expectedValue: "Currency, e.g., $23,200",
		dataType: "Currency",
		section: "financial-details",
	},
	repairsAndMaintenance: {
		fieldId: "repairsAndMaintenance",
		description: "Projected annual R&M.",
		expectedValue: "Currency, e.g., $46,400",
		dataType: "Currency",
		section: "financial-details",
	},
	managementFee: {
		fieldId: "managementFee",
		description: "Projected annual property management fees.",
		expectedValue: "Currency, e.g., $85,000",
		dataType: "Currency",
		section: "financial-details",
	},
	generalAndAdmin: {
		fieldId: "generalAndAdmin",
		description: "Projected annual G&A expenses.",
		expectedValue: "Currency, e.g., $40,600",
		dataType: "Currency",
		section: "financial-details",
	},
	payroll: {
		fieldId: "payroll",
		description: "Projected annual payroll expenses.",
		expectedValue: "Currency, e.g., $174,000",
		dataType: "Currency",
		section: "financial-details",
	},
	reserves: {
		fieldId: "reserves",
		description: "Projected annual replacement reserves.",
		expectedValue: "Currency, e.g., $23,200",
		dataType: "Currency",
		section: "financial-details",
	},
	marketingLeasing: {
		fieldId: "marketingLeasing",
		description: "Projected marketing and leasing costs.",
		expectedValue: "Currency, e.g., $68,040",
		dataType: "Currency",
		section: "financial-details",
	},
	serviceCoordination: {
		fieldId: "serviceCoordination",
		description: "Cost for resident services (if applicable).",
		expectedValue: "Currency, e.g., $0",
		dataType: "Currency",
		section: "financial-details",
	},

	// Investment Metrics
	noiYear1: {
		fieldId: "noiYear1",
		description: "Year 1 Net Operating Income. (EGI - Expenses).",
		expectedValue: "Currency, e.g., $2,268,000",
		dataType: "Currency",
		section: "financial-details",
	},
	yieldOnCost: {
		fieldId: "yieldOnCost",
		description: "Yield on Cost (NOI / TDC).",
		expectedValue: "Percentage, e.g., 7.6%",
		dataType: "Percent",
		section: "financial-details",
	},
	capRate: {
		fieldId: "capRate",
		description: "Market Cap Rate used for valuation.",
		expectedValue: "Percentage, e.g., 5.50%",
		dataType: "Percent",
		section: "financial-details",
	},
	stabilizedValue: {
		fieldId: "stabilizedValue",
		description: "Projected value at stabilization (NOI / Cap Rate).",
		expectedValue: "Currency, e.g., $41,200,000",
		dataType: "Currency",
		section: "financial-details",
	},
	ltv: {
		fieldId: "ltv",
		description: "Loan-to-Value Ratio (Loan / Stabilized Value).",
		expectedValue: "Percentage, e.g., 44%",
		dataType: "Percent",
		section: "financial-details",
	},
	debtYield: {
		fieldId: "debtYield",
		description: "Debt Yield (NOI / Loan Amount).",
		expectedValue: "Percentage, e.g., 12.6%",
		dataType: "Percent",
		section: "financial-details",
	},
	dscr: {
		fieldId: "dscr",
		description: "Debt Service Coverage Ratio (NOI / Debt Service).",
		expectedValue: "Decimal, e.g., 1.25x",
		dataType: "Decimal",
		section: "financial-details",
	},
	trendedNOIYear1: {
		fieldId: "trendedNOIYear1",
		description: "Year 1 NOI with inflation trending applied.",
		expectedValue: "Currency, e.g., $2,313,360",
		dataType: "Currency",
		section: "financial-details",
	},
	untrendedNOIYear1: {
		fieldId: "untrendedNOIYear1",
		description: "Year 1 NOI in current dollars (untrended).",
		expectedValue: "Currency, e.g., $2,222,640",
		dataType: "Currency",
		section: "financial-details",
	},
	trendedYield: {
		fieldId: "trendedYield",
		description: "Yield based on trended NOI.",
		expectedValue: "Percentage, e.g., 7.76%",
		dataType: "Percent",
		section: "financial-details",
	},
	untrendedYield: {
		fieldId: "untrendedYield",
		description: "Yield based on untrended NOI.",
		expectedValue: "Percentage, e.g., 7.45%",
		dataType: "Percent",
		section: "financial-details",
	},
	inflationAssumption: {
		fieldId: "inflationAssumption",
		description: "Annual inflation rate assumption.",
		expectedValue: "Percentage, e.g., 2.0%",
		dataType: "Percent",
		section: "financial-details",
	},
	dscrStressTest: {
		fieldId: "dscrStressTest",
		description: "DSCR at stressed interest rate.",
		expectedValue: "Decimal, e.g., 1.08",
		dataType: "Decimal",
		section: "financial-details",
	},
	portfolioLTV: {
		fieldId: "portfolioLTV",
		description: "Sponsor's portfolio-wide LTV.",
		expectedValue: "Percentage, e.g., 65%",
		dataType: "Percent",
		section: "financial-details",
	},
	irr: {
		fieldId: "irr",
		description: "Internal Rate of Return (IRR) for the project.",
		expectedValue: "Percentage, e.g., 18.5%",
		dataType: "Percent",
		section: "financial-details",
	},
	equityMultiple: {
		fieldId: "equityMultiple",
		description: "Equity Multiple (Total Return / Equity Invested).",
		expectedValue: "Decimal, e.g., 2.3x",
		dataType: "Decimal",
		section: "financial-details",
	},
	breakEven: {
		fieldId: "breakEven",
		description: "Break-even occupancy percentage (1 / DSCR * 100).",
		expectedValue: "Percentage, e.g., 78%",
		dataType: "Percent",
		section: "financial-details",
	},
	riskLevelBase: {
		fieldId: "riskLevelBase",
		description: "Risk level based on base IRR thresholds.",
		expectedValue: "Low, Medium, High",
		dataType: "Dropdown",
		section: "financial-details",
	},
	riskLevelUpside: {
		fieldId: "riskLevelUpside",
		description: "Risk level for upside scenario (IRR * 1.1).",
		expectedValue: "Low, Medium, High",
		dataType: "Dropdown",
		section: "financial-details",
	},
	riskLevelDownside: {
		fieldId: "riskLevelDownside",
		description: "Risk level for downside scenario (IRR * 0.9).",
		expectedValue: "Low, Medium, High",
		dataType: "Dropdown",
		section: "financial-details",
	},
	upsideIRR: {
		fieldId: "upsideIRR",
		description: "IRR for upside scenario (Base IRR * 1.1).",
		expectedValue: "Percentage, e.g., 20.35%",
		dataType: "Percent",
		section: "financial-details",
	},
	downsideIRR: {
		fieldId: "downsideIRR",
		description: "IRR for downside scenario (Base IRR * 0.9).",
		expectedValue: "Percentage, e.g., 16.65%",
		dataType: "Percent",
		section: "financial-details",
	},
	upsideEquityMultiple: {
		fieldId: "upsideEquityMultiple",
		description: "Equity Multiple for upside scenario (Base * 1.1).",
		expectedValue: "Decimal, e.g., 2.53x",
		dataType: "Decimal",
		section: "financial-details",
	},
	downsideEquityMultiple: {
		fieldId: "downsideEquityMultiple",
		description: "Equity Multiple for downside scenario (Base * 0.9).",
		expectedValue: "Decimal, e.g., 2.07x",
		dataType: "Decimal",
		section: "financial-details",
	},
	upsideProfitMargin: {
		fieldId: "upsideProfitMargin",
		description: "Profit margin for upside scenario (Stabilized Value * 1.02).",
		expectedValue: "Percentage, e.g., 38.5%",
		dataType: "Percent",
		section: "financial-details",
	},
	downsideProfitMargin: {
		fieldId: "downsideProfitMargin",
		description: "Profit margin for downside scenario (Stabilized Value * 0.97).",
		expectedValue: "Percentage, e.g., 35.2%",
		dataType: "Percent",
		section: "financial-details",
	},

	// Legacy/Additional Financial Fields
	purchasePrice: {
		fieldId: "purchasePrice",
		description: "Purchase price for acquisition, or basis for refi.",
		expectedValue: "Currency, e.g., $15,000,000",
		dataType: "Currency",
		section: "financials",
	},
	totalProjectCost: {
		fieldId: "totalProjectCost",
		description: "Total cost of the project (TDC).",
		expectedValue: "Currency, e.g., $29,800,000",
		dataType: "Currency",
		section: "financials",
	},
	capexBudget: {
		fieldId: "capexBudget",
		description: "Budget for capital improvements.",
		expectedValue: "Currency, e.g., $1,500,000",
		dataType: "Currency",
		section: "financials",
	},
	propertyNoiT12: {
		fieldId: "propertyNoiT12",
		description: "Trailing 12-month Net Operating Income.",
		expectedValue: "Currency, e.g., $450,000",
		dataType: "Currency",
		section: "financials",
	},
	stabilizedNoiProjected: {
		fieldId: "stabilizedNoiProjected",
		description: "Projected NOI at stabilization.",
		expectedValue: "Currency, e.g., $2,268,000",
		dataType: "Currency",
		section: "financials",
	},
	exitStrategy: {
		fieldId: "exitStrategy",
		description: "Planned strategy for exiting the investment.",
		expectedValue: "Sale, Refinance, Long-Term Hold, Undecided",
		dataType: "Dropdown",
		section: "financials",
	},
	businessPlanSummary: {
		fieldId: "businessPlanSummary",
		description: "Summary of the business plan and value-add strategy.",
		expectedValue: "Text description of business plan",
		dataType: "Textarea",
		section: "financials",
	},
	marketOverviewSummary: {
		fieldId: "marketOverviewSummary",
		description: "Summary of market conditions and trends.",
		expectedValue: "Text description of market",
		dataType: "Textarea",
		section: "financials",
	},
	equityCommittedPercent: {
		fieldId: "equityCommittedPercent",
		description: "Percentage of equity already committed.",
		expectedValue: "Percentage, e.g., 100%",
		dataType: "Percent",
		section: "financials",
	},

	// Section 4: Market Context
	submarketName: {
		fieldId: "submarketName",
		description: "Name of the submarket.",
		expectedValue: "e.g., Downtown Dallas",
		dataType: "Text",
		section: "market-context",
	},
	distanceToCBD: {
		fieldId: "distanceToCBD",
		description: "Distance to the Central Business District.",
		expectedValue: "Decimal, e.g., 2.1 miles",
		dataType: "Decimal",
		section: "market-context",
	},
	distanceToEmployment: {
		fieldId: "distanceToEmployment",
		description: "Distance to major employment hubs.",
		expectedValue: 'Text, e.g., "2.1 miles"',
		dataType: "Text",
		section: "market-context",
	},
	distanceToTransit: {
		fieldId: "distanceToTransit",
		description: "Distance to nearest public transit.",
		expectedValue: "Decimal, e.g., 0.5 miles",
		dataType: "Decimal",
		section: "market-context",
	},
	walkabilityScore: {
		fieldId: "walkabilityScore",
		description: "Walk Score (0-100).",
		expectedValue: "Integer, 0-100, e.g., 85",
		dataType: "Integer",
		section: "market-context",
	},
	population3Mi: {
		fieldId: "population3Mi",
		description: "Population within a 3-mile radius.",
		expectedValue: "Integer, e.g., 174,270",
		dataType: "Integer",
		section: "market-context",
	},
	popGrowth201020: {
		fieldId: "popGrowth201020",
		description: "Historical population growth (2010-2020).",
		expectedValue: "Percentage, e.g., 23.3%",
		dataType: "Percent",
		section: "market-context",
	},
	projGrowth202429: {
		fieldId: "projGrowth202429",
		description: "Projected population growth (2024-2029).",
		expectedValue: "Percentage, e.g., 6.9%",
		dataType: "Percent",
		section: "market-context",
	},
	medianHHIncome: {
		fieldId: "medianHHIncome",
		description: "Median Household Income within 3 miles.",
		expectedValue: "Currency, e.g., $85,906",
		dataType: "Currency",
		section: "market-context",
	},
	renterOccupiedPercent: {
		fieldId: "renterOccupiedPercent",
		description: "Percentage of renter-occupied households.",
		expectedValue: "Percentage, e.g., 76.7%",
		dataType: "Percent",
		section: "market-context",
	},
	bachelorsDegreePercent: {
		fieldId: "bachelorsDegreePercent",
		description: "Percentage of population with a bachelor's degree.",
		expectedValue: "Percentage, e.g., 50.2%",
		dataType: "Percent",
		section: "market-context",
	},
	msaName: {
		fieldId: "msaName",
		description: "Metropolitan Statistical Area (MSA) name.",
		expectedValue: 'Text, e.g., "Dallas-Fort Worth-Arlington, TX"',
		dataType: "Text",
		section: "market-context",
	},
	unemploymentRate: {
		fieldId: "unemploymentRate",
		description: "Local unemployment rate.",
		expectedValue: "Percentage, e.g., 3.5%",
		dataType: "Percent",
		section: "market-context",
	},
	largestEmployer: {
		fieldId: "largestEmployer",
		description: "Name of the largest employer in the area.",
		expectedValue: 'Text, e.g., "Downtown Dallas"',
		dataType: "Text",
		section: "market-context",
	},
	employerConcentration: {
		fieldId: "employerConcentration",
		description: "Percent of jobs from top employer.",
		expectedValue: "Percentage, e.g., 15%",
		dataType: "Percent",
		section: "market-context",
	},
	submarketAbsorption: {
		fieldId: "submarketAbsorption",
		description: "Annual net absorption in submarket.",
		expectedValue: "Integer, e.g., 500",
		dataType: "Integer",
		section: "market-context",
	},
	supplyPipeline: {
		fieldId: "supplyPipeline",
		description: "Total units under construction + planned.",
		expectedValue: "Integer, e.g., 1200",
		dataType: "Integer",
		section: "market-context",
	},
	monthsOfSupply: {
		fieldId: "monthsOfSupply",
		description: "Months of supply based on absorption.",
		expectedValue: "Decimal, e.g., 8.5",
		dataType: "Decimal",
		section: "market-context",
	},
	marketStatus: {
		fieldId: "marketStatus",
		description: "Market status based on occupancy thresholds (Tight/Balanced/Soft).",
		expectedValue: "Tight, Balanced, Soft",
		dataType: "Dropdown",
		section: "market-context",
	},
	demandTrend: {
		fieldId: "demandTrend",
		description: "Demand trend based on job and population growth.",
		expectedValue: "↑ Growing, → Stable, ↓ Declining",
		dataType: "Dropdown",
		section: "market-context",
	},
	supplyPressure: {
		fieldId: "supplyPressure",
		description: "Supply pressure level based on months of supply.",
		expectedValue: "Low, Moderate, High",
		dataType: "Dropdown",
		section: "market-context",
	},
	totalJobs: {
		fieldId: "totalJobs",
		description: "Total jobs from major employers in the area.",
		expectedValue: "Integer, e.g., 42,000",
		dataType: "Integer",
		section: "market-context",
	},
	avgGrowth: {
		fieldId: "avgGrowth",
		description: "Average growth rate from major employers.",
		expectedValue: "Percentage, e.g., 8.2%",
		dataType: "Percent",
		section: "market-context",
	},
	captureRate: {
		fieldId: "captureRate",
		description: "Project's required capture rate of demand.",
		expectedValue: "Percentage, e.g., 2.1%",
		dataType: "Percent",
		section: "market-context",
	},
	marketConcessions: {
		fieldId: "marketConcessions",
		description: "Typical concessions in the market.",
		expectedValue: 'Text, e.g., "1 Month Free"',
		dataType: "Text",
		section: "market-context",
	},
	northStarComp: {
		fieldId: "northStarComp",
		description: "The primary competitor/comparable property.",
		expectedValue: 'Text, e.g., "The Alexan Deep Ellum"',
		dataType: "Text",
		section: "market-context",
	},
	substantialComp: {
		fieldId: "substantialComp",
		description: "Substantial comparable property used for market analysis.",
		expectedValue: 'Text, e.g., "Property name or address"',
		dataType: "Text",
		section: "market-context",
	},
	infrastructureCatalyst: {
		fieldId: "infrastructureCatalyst",
		description: "Key infrastructure project driving demand.",
		expectedValue: 'Text, e.g., "New Light Rail Station"',
		dataType: "Text",
		section: "market-context",
	},
	broadbandSpeed: {
		fieldId: "broadbandSpeed",
		description: "Available broadband speed.",
		expectedValue: 'Text, e.g., "Fiber 1Gbps Available"',
		dataType: "Text",
		section: "market-context",
	},
	crimeRiskLevel: {
		fieldId: "crimeRiskLevel",
		description: "Crime risk level for the area.",
		expectedValue: "Low, Moderate, High",
		dataType: "Dropdown",
		section: "market-context",
	},

	// Section 5: Special Considerations
	opportunityZone: {
		fieldId: "opportunityZone",
		description: "Is the property in a Qualified Opportunity Zone?",
		expectedValue: "Yes/No (Boolean)",
		dataType: "Boolean",
		section: "special-considerations",
	},
	affordableHousing: {
		fieldId: "affordableHousing",
		description: "Does the project include affordable housing?",
		expectedValue: "Yes/No (Boolean)",
		dataType: "Boolean",
		section: "special-considerations",
	},
	affordableUnitsNumber: {
		fieldId: "affordableUnitsNumber",
		description: "Number of affordable units.",
		expectedValue: "Integer, e.g., 58",
		dataType: "Integer",
		section: "special-considerations",
	},
	amiTargetPercent: {
		fieldId: "amiTargetPercent",
		description: "AMI target for affordable units.",
		expectedValue: "Percentage, e.g., 80% AMI",
		dataType: "Percent",
		section: "special-considerations",
	},
	taxExemption: {
		fieldId: "taxExemption",
		description: "Is there a tax exemption?",
		expectedValue: "Yes/No (Boolean)",
		dataType: "Boolean",
		section: "special-considerations",
	},
	tifDistrict: {
		fieldId: "tifDistrict",
		description: "Is the property in a TIF District?",
		expectedValue: "Yes/No (Boolean)",
		dataType: "Boolean",
		section: "special-considerations",
	},
	taxAbatement: {
		fieldId: "taxAbatement",
		description: "Is there a tax abatement?",
		expectedValue: "Yes/No (Boolean)",
		dataType: "Boolean",
		section: "special-considerations",
	},
	paceFinancing: {
		fieldId: "paceFinancing",
		description: "Is PACE financing being used?",
		expectedValue: "Yes/No (Boolean)",
		dataType: "Boolean",
		section: "special-considerations",
	},
	historicTaxCredits: {
		fieldId: "historicTaxCredits",
		description: "Are Historic Tax Credits (HTC) being used?",
		expectedValue: "Yes/No (Boolean)",
		dataType: "Boolean",
		section: "special-considerations",
	},
	newMarketsCredits: {
		fieldId: "newMarketsCredits",
		description: "Are New Markets Tax Credits (NMTC) being used?",
		expectedValue: "Yes/No (Boolean)",
		dataType: "Boolean",
		section: "special-considerations",
	},
	exemptionStructure: {
		fieldId: "exemptionStructure",
		description: "Structure of the tax exemption.",
		expectedValue: "PFC, MMD, PILOT",
		dataType: "Dropdown",
		section: "special-considerations",
	},
	sponsoringEntity: {
		fieldId: "sponsoringEntity",
		description: "Public sponsoring entity for the exemption.",
		expectedValue: 'Text, e.g., "SoGood MMD"',
		dataType: "Text",
		section: "special-considerations",
	},
	exemptionTerm: {
		fieldId: "exemptionTerm",
		description: "Term of the tax exemption.",
		expectedValue: "Integer, e.g., 15",
		dataType: "Integer",
		section: "special-considerations",
	},
	incentiveStacking: {
		fieldId: "incentiveStacking",
		description:
			"Comma-separated list of stacked incentives derived from enabled incentive flags.",
		expectedValue: 'Text, e.g., "Opportunity Zone, Tax Abatement"',
		dataType: "Text",
		section: "special-considerations",
	},
	relocationPlan: {
		fieldId: "relocationPlan",
		description: "Status of tenant relocation plan.",
		expectedValue: "Complete, In Process, N/A",
		dataType: "Dropdown",
		section: "special-considerations",
	},
	seismicPMLRisk: {
		fieldId: "seismicPMLRisk",
		description: "Seismic Probable Maximum Loss (PML) percentage.",
		expectedValue: 'Text, e.g., "2.5% PML"',
		dataType: "Text",
		section: "special-considerations",
	},
	impactFees: {
		fieldId: "impactFees",
		description: "Impact fees per square foot for the project.",
		expectedValue: "Currency per SF, e.g., $12/SF",
		dataType: "Currency",
		section: "special-considerations",
	},
	totalIncentiveValue: {
		fieldId: "totalIncentiveValue",
		description: "Total value of all incentives (tax abatement, impact fees, etc.).",
		expectedValue: "Currency, e.g., $2,400,000",
		dataType: "Currency",
		section: "special-considerations",
	},

	// Section 6: Timeline & Milestones
	landAcqClose: {
		fieldId: "landAcqClose",
		description: "Date of land acquisition closing.",
		expectedValue: "Date",
		dataType: "Date",
		section: "timeline",
	},
	entitlements: {
		fieldId: "entitlements",
		description: "Status of entitlements.",
		expectedValue: "Approved/Pending",
		dataType: "Dropdown",
		section: "timeline",
	},
	finalPlans: {
		fieldId: "finalPlans",
		description: "Status of final architectural plans.",
		expectedValue: "Approved/Pending",
		dataType: "Dropdown",
		section: "timeline",
	},
	permitsIssued: {
		fieldId: "permitsIssued",
		description: "Status of building permits.",
		expectedValue: "Issued/Pending",
		dataType: "Dropdown",
		section: "timeline",
	},
	verticalStart: {
		fieldId: "verticalStart",
		description: "Date for start of vertical construction.",
		expectedValue: "Date",
		dataType: "Date",
		section: "timeline",
	},
	firstOccupancy: {
		fieldId: "firstOccupancy",
		description: "Date of first occupancy.",
		expectedValue: "Date",
		dataType: "Date",
		section: "timeline",
	},
	stabilization: {
		fieldId: "stabilization",
		description: "Projected stabilization date.",
		expectedValue: "Date",
		dataType: "Date",
		section: "timeline",
	},
	preLeasedSF: {
		fieldId: "preLeasedSF",
		description: "Pre-leased square footage.",
		expectedValue: "Integer, e.g., 30,000",
		dataType: "Integer",
		section: "timeline",
	},

	drawSchedule: {
		fieldId: "drawSchedule",
		description: "Construction draw schedule.",
		expectedValue: "Table/Object with drawNumber, percentComplete, amount",
		dataType: "Table",
		section: "timeline",
	},
	absorptionProjection: {
		fieldId: "absorptionProjection",
		description: "Projected monthly absorption (units/month).",
		expectedValue: "Integer, e.g., 12",
		dataType: "Integer",
		section: "timeline",
	},
	opDeficitEscrow: {
		fieldId: "opDeficitEscrow",
		description: "Escrow for operating deficits during lease-up.",
		expectedValue: "Currency, e.g., $650,000",
		dataType: "Currency",
		section: "timeline",
	},
	leaseUpEscrow: {
		fieldId: "leaseUpEscrow",
		description: "Lease-up escrow amount.",
		expectedValue: "Currency, e.g., $1,300,000",
		dataType: "Currency",
		section: "timeline",
	},

	// Section 7: Site & Context
	totalSiteAcreage: {
		fieldId: "totalSiteAcreage",
		description: "Total acreage of the site.",
		expectedValue: "Decimal, e.g., 2.5 acres",
		dataType: "Decimal",
		section: "site-context",
	},
	currentSiteStatus: {
		fieldId: "currentSiteStatus",
		description: "Current condition of the site.",
		expectedValue: "Vacant/Existing",
		dataType: "Dropdown",
		section: "site-context",
	},
	topography: {
		fieldId: "topography",
		description: "Topography of the site.",
		expectedValue: "Flat/Sloped",
		dataType: "Dropdown",
		section: "site-context",
	},
	environmental: {
		fieldId: "environmental",
		description: "Environmental status summary.",
		expectedValue: "Clean/Remediation",
		dataType: "Dropdown",
		section: "site-context",
	},
	utilities: {
		fieldId: "utilities",
		description: "Availability of utilities at the site.",
		expectedValue: "Available/None",
		dataType: "Dropdown",
		section: "site-context",
	},
	siteAccess: {
		fieldId: "siteAccess",
		description: "Description of site access and egress.",
		expectedValue: 'Text, e.g., "Hickory St, Ferris St"',
		dataType: "Text",
		section: "site-context",
	},
	proximityShopping: {
		fieldId: "proximityShopping",
		description: "Proximity to shopping centers.",
		expectedValue: 'Text, e.g., "Farmers Market, Deep Ellum nearby"',
		dataType: "Text",
		section: "site-context",
	},
	proximityRestaurants: {
		fieldId: "proximityRestaurants",
		description: "Proximity to restaurants.",
		expectedValue: "Text",
		dataType: "Text",
		section: "site-context",
	},
	proximityParks: {
		fieldId: "proximityParks",
		description: "Proximity to parks.",
		expectedValue: "Text",
		dataType: "Text",
		section: "site-context",
	},
	proximitySchools: {
		fieldId: "proximitySchools",
		description: "Proximity to schools.",
		expectedValue: "Text",
		dataType: "Text",
		section: "site-context",
	},
	proximityHospitals: {
		fieldId: "proximityHospitals",
		description: "Proximity to hospitals.",
		expectedValue: "Text",
		dataType: "Text",
		section: "site-context",
	},
	buildableAcreage: {
		fieldId: "buildableAcreage",
		description:
			"Acreage suitable for building (net of wetlands/easements).",
		expectedValue: "Decimal, e.g., 2.3 acres",
		dataType: "Decimal",
		section: "site-context",
	},
	allowableFAR: {
		fieldId: "allowableFAR",
		description: "Allowable Floor Area Ratio per zoning.",
		expectedValue: "Decimal, e.g., 3.5",
		dataType: "Decimal",
		section: "site-context",
	},
	farUtilizedPercent: {
		fieldId: "farUtilizedPercent",
		description: "Percentage of allowable FAR utilized.",
		expectedValue: "Percentage, e.g., 85%",
		dataType: "Percent",
		section: "site-context",
	},
	heightLimit: {
		fieldId: "heightLimit",
		description: "Maximum building height allowed by zoning (in feet).",
		expectedValue: "Integer, e.g., 240",
		dataType: "Integer",
		section: "site-context",
	},
	zoningCompliant: {
		fieldId: "zoningCompliant",
		description: "Whether the project complies with zoning requirements.",
		expectedValue: "Compliant, Non-Compliant",
		dataType: "Dropdown",
		section: "site-context",
	},
	densityBonus: {
		fieldId: "densityBonus",
		description: "Is a density bonus being utilized?",
		expectedValue: "Yes/No (Boolean)",
		dataType: "Boolean",
		section: "site-context",
	},
	soilConditions: {
		fieldId: "soilConditions",
		description: "Summary of soil conditions.",
		expectedValue: 'Text, e.g., "Expansive Clay, req Piles"',
		dataType: "Text",
		section: "site-context",
	},
	floodZone: {
		fieldId: "floodZone",
		description: "FEMA Flood Zone designation.",
		expectedValue: 'Text, e.g., "Zone X" or "Zone AE"',
		dataType: "Text",
		section: "site-context",
	},
	wetlandsPresent: {
		fieldId: "wetlandsPresent",
		description: "Presence of wetlands.",
		expectedValue: "Yes/No (Boolean)",
		dataType: "Boolean",
		section: "site-context",
	},
	seismicRisk: {
		fieldId: "seismicRisk",
		description: "Seismic risk category.",
		expectedValue: "Low, Moderate, High",
		dataType: "Dropdown",
		section: "site-context",
	},
	phaseIESAFinding: {
		fieldId: "phaseIESAFinding",
		description: "Findings from Phase I ESA.",
		expectedValue: "Clean, REC, HREC",
		dataType: "Dropdown",
		section: "site-context",
	},
	utilityAvailability: {
		fieldId: "utilityAvailability",
		description: "Detailed utility availability status.",
		expectedValue: "Text description of utility availability",
		dataType: "Text",
		section: "site-context",
	},
	easements: {
		fieldId: "easements",
		description: "Description of easements affecting the site.",
		expectedValue: 'Text, e.g., "Utility easement on north side"',
		dataType: "Text",
		section: "site-context",
	},
	accessPoints: {
		fieldId: "accessPoints",
		description: "Number/location of access points.",
		expectedValue: 'Text, e.g., "1 Curb Cut on Main St"',
		dataType: "Text",
		section: "site-context",
	},
	adjacentLandUse: {
		fieldId: "adjacentLandUse",
		description: "Usage of adjacent land.",
		expectedValue: 'Text, e.g., "Heavy Industrial" (Risk)',
		dataType: "Text",
		section: "site-context",
	},
	noiseFactors: {
		fieldId: "noiseFactors",
		description: "Sources of noise pollution.",
		expectedValue: "Highway, Rail, Airport, None (multi-select)",
		dataType: "Multi-select",
		section: "site-context",
	},
	viewCorridors: {
		fieldId: "viewCorridors",
		description: "Significant views from the property.",
		expectedValue: "Skyline, Water, Park, None (multi-select)",
		dataType: "Multi-select",
		section: "site-context",
	},
	topEmployers: {
		fieldId: "topEmployers",
		description: "Major employers near the site.",
		expectedValue: "Text, e.g., 'Hospital, University'",
		dataType: "Text",
		section: "market-context",
	},
	infrastructureProject: {
		fieldId: "infrastructureProject",
		description: "Major nearby infrastructure project.",
		expectedValue: "Text",
		dataType: "Text",
		section: "market-context",
	},
	infraCompletion: {
		fieldId: "infraCompletion",
		description: "Completion date for infrastructure project.",
		expectedValue: "Date/Year",
		dataType: "Text",
		section: "market-context",
	},
	projectBudget: {
		fieldId: "projectBudget",
		description: "Total budget for the infrastructure project.",
		expectedValue: "Currency",
		dataType: "Currency",
		section: "market-context",
	},
	utilityCapacity: {
		fieldId: "utilityCapacity",
		description: "Capacity details for utilities.",
		expectedValue: "Text",
		dataType: "Text",
		section: "site-context",
	},
	geotechSoilsRep: {
		fieldId: "geotechSoilsRep",
		description: "Summary of geotechnical report findings.",
		expectedValue: "Text",
		dataType: "Text",
		section: "site-context",
	},

	// Section 8: Sponsor Information
	sponsorEntityName: {
		fieldId: "sponsorEntityName",
		description: "Name of the sponsor entity.",
		expectedValue: "e.g., Hoque Global",
		dataType: "Text",
		section: "sponsor-info",
	},
	sponsorStructure: {
		fieldId: "sponsorStructure",
		description: "Legal structure of the sponsor.",
		expectedValue: 'Text, e.g., "General Partner"',
		dataType: "Text",
		section: "sponsor-info",
	},
	equityPartner: {
		fieldId: "equityPartner",
		description: "Name of equity partner.",
		expectedValue: "e.g., ACARA",
		dataType: "Text",
		section: "sponsor-info",
	},
	contactInfo: {
		fieldId: "contactInfo",
		description: "Contact information for sponsor key principals.",
		expectedValue: 'Text, e.g., "Name (Phone), Name (Phone)"',
		dataType: "Text",
		section: "sponsor-info",
	},
	sponsorExpScore: {
		fieldId: "sponsorExpScore",
		description: "Calculated sponsor experience score (0-10).",
		expectedValue: "Integer, 0-10, e.g., 8",
		dataType: "Integer",
		section: "sponsor-info",
	},
	priorDevelopments: {
		fieldId: "priorDevelopments",
		description: "Number of prior development units completed.",
		expectedValue: "Integer, e.g., 500",
		dataType: "Integer",
		section: "sponsor-info",
	},
	netWorth: {
		fieldId: "netWorth",
		description: "Sponsor/Guarantor Net Worth.",
		expectedValue: "Currency, e.g., $45,000,000",
		dataType: "Currency",
		section: "sponsor-info",
	},
	guarantorLiquidity: {
		fieldId: "guarantorLiquidity",
		description: "Liquidity of guarantor(s).",
		expectedValue: "Currency, e.g., $2,500,000",
		dataType: "Currency",
		section: "sponsor-info",
	},
	portfolioDSCR: {
		fieldId: "portfolioDSCR",
		description: "Global DSCR of sponsor's portfolio.",
		expectedValue: "Decimal, e.g., 1.35",
		dataType: "Decimal",
		section: "sponsor-info",
	},
	internalAdvisorNotes: {
		fieldId: "internalAdvisorNotes",
		description: "Internal notes for advisor use.",
		expectedValue: "Text",
		dataType: "Textarea",
		section: "financials",
	},

	// Residential Unit Mix Table (container)
	residentialUnitMix: {
		fieldId: "residentialUnitMix",
		description:
			"Breakdown of residential unit types, counts, sizes, and rents.",
		expectedValue:
			"Array of rows with unitType, unitCount, avgSF, monthlyRent, totalSF",
		dataType: "Table",
		section: "property-specs",
	},

	// Residential Unit Mix Table - Column Fields
	unitType: {
		fieldId: "unitType",
		description: "Unit type identifier.",
		expectedValue: 'Text, e.g., "Studio", "1BR"',
		dataType: "Text",
		section: "property-specs",
	},
	unitCount: {
		fieldId: "unitCount",
		description: "Count of units.",
		expectedValue: "Integer",
		dataType: "Integer",
		section: "property-specs",
	},
	avgSF: {
		fieldId: "avgSF",
		description: "Average square footage.",
		expectedValue: "Integer",
		dataType: "Integer",
		section: "property-specs",
	},
	monthlyRent: {
		fieldId: "monthlyRent",
		description: "Monthly rent per unit.",
		expectedValue: "Currency",
		dataType: "Currency",
		section: "property-specs",
	},
	affordabilityStatus: {
		fieldId: "affordabilityStatus",
		description: "Affordability designation.",
		expectedValue: 'Text, e.g., "Market Rate"',
		dataType: "Text",
		section: "property-specs",
	},
	amiTargetPercentColumn: {
		fieldId: "amiTargetPercentColumn",
		description: "AMI Target %.",
		expectedValue: "Percentage",
		dataType: "Percent",
		section: "property-specs",
	},
	rentBumpSchedule: {
		fieldId: "rentBumpSchedule",
		description: "Planned rent increases.",
		expectedValue: "Text",
		dataType: "Text",
		section: "property-specs",
	},

	// Commercial Space Mix Table (container)
	commercialSpaceMix: {
		fieldId: "commercialSpaceMix",
		description:
			"Breakdown of commercial space types, square footage, tenants, lease terms and rents.",
		expectedValue:
			"Array of rows with spaceType, squareFootage, tenant, leaseTerm, annualRent",
		dataType: "Table",
		section: "property-specs",
	},

	// Commercial Space Mix Table - Column Fields
	spaceType: {
		fieldId: "spaceType",
		description: "Type of commercial space.",
		expectedValue: 'Text, e.g., "Retail"',
		dataType: "Text",
		section: "property-specs",
	},
	squareFootage: {
		fieldId: "squareFootage",
		description: "Square footage.",
		expectedValue: "Integer",
		dataType: "Integer",
		section: "property-specs",
	},
	tenant: {
		fieldId: "tenant",
		description: "Tenant name.",
		expectedValue: "Text",
		dataType: "Text",
		section: "property-specs",
	},
	leaseTerm: {
		fieldId: "leaseTerm",
		description: "Lease term.",
		expectedValue: "Text",
		dataType: "Text",
		section: "property-specs",
	},
	annualRent: {
		fieldId: "annualRent",
		description: "Annual rent.",
		expectedValue: "Currency",
		dataType: "Currency",
		section: "property-specs",
	},
	tiAllowance: {
		fieldId: "tiAllowance",
		description: "Tenant Improvement Allowance.",
		expectedValue: "Currency",
		dataType: "Currency",
		section: "property-specs",
	},

	// Rent Comps Table (container)
	rentComps: {
		fieldId: "rentComps",
		description:
			"Comparable rent properties used to benchmark subject rents.",
		expectedValue:
			"Array of rows with propertyName, address, distance, yearBuilt, totalUnits, occupancyPercent, avgRentMonth, rentPSF",
		dataType: "Table",
		section: "market-context",
	},

	// Rent Comps Table - Column Fields
	compPropertyName: {
		fieldId: "compPropertyName",
		description: "Comparable property name.",
		expectedValue: "Text",
		dataType: "Text",
		section: "market-context",
	},
	compAddress: {
		fieldId: "compAddress",
		description: "Comparable address.",
		expectedValue: "Text",
		dataType: "Text",
		section: "market-context",
	},
	compDistance: {
		fieldId: "compDistance",
		description: "Distance to comparable.",
		expectedValue: "Decimal",
		dataType: "Decimal",
		section: "market-context",
	},
	compYearBuilt: {
		fieldId: "compYearBuilt",
		description: "Year built.",
		expectedValue: "Integer",
		dataType: "Integer",
		section: "market-context",
	},
	compTotalUnits: {
		fieldId: "compTotalUnits",
		description: "Total units.",
		expectedValue: "Integer",
		dataType: "Integer",
		section: "market-context",
	},
	compOccupancyPercent: {
		fieldId: "compOccupancyPercent",
		description: "Occupancy percentage.",
		expectedValue: "Percentage",
		dataType: "Percent",
		section: "market-context",
	},
	compAvgRentMonth: {
		fieldId: "compAvgRentMonth",
		description: "Average monthly rent.",
		expectedValue: "Currency",
		dataType: "Currency",
		section: "market-context",
	},
	compRentPSF: {
		fieldId: "compRentPSF",
		description: "Rent per square foot.",
		expectedValue: "Currency",
		dataType: "Currency",
		section: "market-context",
	},
	compConcessions: {
		fieldId: "compConcessions",
		description: "Concessions offered.",
		expectedValue: "Text",
		dataType: "Text",
		section: "market-context",
	},

	// Sale Comps Table - Column Fields
	saleCompPropertyName: {
		fieldId: "saleCompPropertyName",
		description: "Comparable sale property name.",
		expectedValue: "Text",
		dataType: "Text",
		section: "market-context",
	},
	salePricePerUnit: {
		fieldId: "salePricePerUnit",
		description: "Sale price per unit.",
		expectedValue: "Currency",
		dataType: "Currency",
		section: "market-context",
	},
	saleCompCapRate: {
		fieldId: "saleCompCapRate",
		description: "Cap rate at sale.",
		expectedValue: "Percentage",
		dataType: "Percent",
		section: "market-context",
	},
	saleDate: {
		fieldId: "saleDate",
		description: "Date of sale.",
		expectedValue: "Date",
		dataType: "Date",
		section: "market-context",
	},

	// Draw Schedule Table - Column Fields
	drawNumber: {
		fieldId: "drawNumber",
		description: "Draw number.",
		expectedValue: "Integer",
		dataType: "Integer",
		section: "timeline",
	},
	percentComplete: {
		fieldId: "percentComplete",
		description: "Percentage complete.",
		expectedValue: "Percentage",
		dataType: "Percent",
		section: "timeline",
	},
	drawAmount: {
		fieldId: "drawAmount",
		description: "Draw amount.",
		expectedValue: "Currency",
		dataType: "Currency",
		section: "timeline",
	},
};

/**
 * Get metadata for a specific field
 */
export const getFieldMetadata = (
	fieldId: string
): FieldMetadata | undefined => {
	return projectResumeFieldMetadata[fieldId];
};

/**
 * Get all fields for a specific section
 */
export const getFieldsForSection = (section: string): FieldMetadata[] => {
	return Object.values(projectResumeFieldMetadata).filter(
		(field) => field.section === section
	);
};
