// src/services/mockOMData.ts

export const projectOverview = {
  projectName: "SoGood Apartments",
  masterPlan: {
    name: "SoGood Master Planned Development",
    phase: "Building B",
  },
  address: {
    street: "2300 Hickory St",
    city: "Dallas",
    state: "TX",
    zip: "75215",
    county: "Dallas County",
  },
  propertyStats: {
    totalResidentialUnits: 116,
    affordableUnits: 58,
    totalResidentialNRSF: 59_520,
    totalCommercialGRSF: 49_569,
    grossBuildingArea: 127_406,
    averageUnitSize: 513,
    parkingSpaces: 180,
    parkingRatio: 1.55,
    stories: 6,
    buildingType: "Mid-rise / Podium",
    constructionType: "Ground-Up",
    totalDevelopmentCost: 29_807_800,
    loanAmountRequested: 18_000_000,
    yieldOnCost: 7.6,
    capRate: 5.5,
    stabilizedValue: 41_200_000,
    dscr: 1.25,
    debtYield: 12.6,
    noiYear1: 2_268_000,
  },
  schedule: {
    groundbreaking: "2025-08-01",
    completion: "2027-09-30",
    firstOccupancy: "2027-10-15",
    stabilization: "2028-03-31",
  },
  narrativeHighlights: [
    "Phase B of the mixed-use SoGood master plan adjacent to Dallas Farmers Market and Deep Ellum.",
    "30,000 SF Innovation Center is pre-leased to GSV Holdings, anchoring the commercial program.",
    "Workforce housing covenant dedicates 50% of units to households earning ≤80% AMI under a Dallas PFC lease structure.",
  ],
  contacts: {
    sponsor: "Hoque Global",
    equityPartner: "ACARA",
    primaryContacts: [
      { name: "Cody Field", phone: "415.202.3258" },
      { name: "Joel Heikenfeld", phone: "972.455.1943" },
    ],
  },
};

export const scenarioData = {
  base: {
    loanAmount: 18_000_000,
    ltv: 44,
    ltc: 60,
    dscr: 1.25,
    debtYield: 12.6,
    irr: 17.5,
    equityMultiple: 1.95,
    rentGrowth: 3.0,
    exitCap: 5.5,
    constructionCost: 29_807_800,
    vacancy: 7,
    noi: 2_268_000,
  },
  upside: {
    loanAmount: 18_500_000,
    ltv: 46,
    ltc: 62,
    dscr: 1.35,
    debtYield: 13.8,
    irr: 21.2,
    equityMultiple: 2.3,
    rentGrowth: 4.2,
    exitCap: 5.25,
    constructionCost: 30_200_000,
    vacancy: 5,
    noi: 2_420_000,
  },
  downside: {
    loanAmount: 17_000_000,
    ltv: 42,
    ltc: 58,
    dscr: 1.15,
    debtYield: 11.0,
    irr: 13.4,
    equityMultiple: 1.6,
    rentGrowth: 2.0,
    exitCap: 5.85,
    constructionCost: 30_500_000,
    vacancy: 10,
    noi: 2_050_000,
  },
};

export const timelineData = [
  { phase: "Term Sheet Circulation", date: "2024-11-15", status: "completed" },
  { phase: "Due Diligence", date: "2025-02-28", status: "completed" },
  { phase: "Groundbreaking", date: "2025-08-01", status: "current" },
  { phase: "Topping Out", date: "2026-11-15", status: "upcoming" },
  { phase: "Substantial Completion", date: "2027-09-30", status: "upcoming" },
];

export const unitMixData = [
  { type: "Studios", units: 84, avgSF: 385, avgRent: 1_499 },
  { type: "1BR", units: 24, avgSF: 759, avgRent: 1_777 },
  { type: "2BR", units: 8, avgSF: 1_120, avgRent: 2_572 },
];

export const marketComps = [
  { name: "The Hamilton", yearBuilt: 2020, units: 329, rentPSF: 3.05, capRate: 4.9 },
  { name: "The Gabriella", yearBuilt: 2020, units: 364, rentPSF: 3.10, capRate: 4.7 },
  { name: "Broadstone Ambrose", yearBuilt: 2021, units: 171, rentPSF: 2.95, capRate: 5.1 },
  { name: "Novel Deep Ellum", yearBuilt: 2022, units: 231, rentPSF: 3.25, capRate: 4.8 },
  { name: "The Academic", yearBuilt: 2023, units: 365, rentPSF: 3.35, capRate: 4.6 },
];

export const employerData = [
  { name: "AT&T Discovery District", employees: 5_200, growth: 6 },
  { name: "Baylor Univ. Medical Center", employees: 7_800, growth: 3 },
  { name: "Dallas County Government", employees: 4_200, growth: 1 },
  { name: "JP Morgan Chase Regional HQ", employees: 5_100, growth: 5 },
  { name: "Pegasus Park BioLabs", employees: 3_400, growth: 8 },
];

export const sponsorDeals = [
  { project: "Farmers Market Tower", year: 2022, size: 38_000_000, irr: 21.0, multiple: 2.0 },
  { project: "Dallas Innovation Lofts", year: 2020, size: 31_000_000, irr: 19.3, multiple: 1.9 },
  { project: "Deep Ellum Gateway", year: 2019, size: 26_500_000, irr: 23.5, multiple: 2.2 },
  { project: "Cedars Junction", year: 2021, size: 29_000_000, irr: 20.5, multiple: 2.0 },
  { project: "South Dallas Workforce Portfolio", year: 2018, size: 24_000_000, irr: 24.0, multiple: 2.4 },
];

export const dealSnapshotDetails = {
  keyTerms: {
    loanType: "Senior Construction Loan",
    rate: "8.00% (SOFR + ~275 bps)",
    floor: "4.50%",
    term: "24 months",
    extension: "Two 6-month options",
    recourse: "Partial recourse / completion guaranty",
    origination: "1.00%",
    exitFee: "0.50%",
    prepayment: "Minimum interest make-whole",
    lenderReserves: {
      interest: "12 months",
      taxInsurance: "Funded quarterly",
      capEx: "$250,000",
    },
    covenants: {
      minDSCR: "1.20x",
      maxLTV: "60% LTC / 44% LTV",
      minLiquidity: "$2,000,000",
      completionGuaranty: "Full completion guaranty",
    },
  },
  milestones: [
    { phase: "Site Control & PFC Approval", date: "2024-07-12", status: "completed", duration: 30 },
    { phase: "Design Development Complete", date: "2024-11-01", status: "completed", duration: 45 },
    { phase: "Debt Marketing / DD", date: "2025-02-28", status: "completed", duration: 60 },
    { phase: "Groundbreaking", date: "2025-08-01", status: "current", duration: 60 },
    { phase: "Topping Out", date: "2026-11-15", status: "upcoming", duration: 45 },
    { phase: "Substantial Completion", date: "2027-09-30", status: "upcoming", duration: 60 },
  ],
  riskMatrix: {
    high: [],
    medium: [
      {
        risk: "Construction Cost Escalation",
        mitigation: "GMP contract with 5% contingency and periodic buy-out audits",
        probability: "28%",
      },
      {
        risk: "Lease-Up Velocity",
        mitigation: "50% workforce units paired with committed Innovation Center tenancy",
        probability: "22%",
      },
      {
        risk: "Capital Stack Timing",
        mitigation: "LP equity soft-circled; closing concurrent with PFC ground lease",
        probability: "18%",
      },
    ],
    low: [
      {
        risk: "Entitlement / Permitting",
        mitigation: "PD-317 approvals and building permits in hand",
        probability: "5%",
      },
      {
        risk: "Market Demand",
        mitigation: "Downtown Dallas rent growth 6.9% 5-yr; 30k SF pre-leased",
        probability: "12%",
      },
      {
        risk: "Environmental / OZ Compliance",
        mitigation: "Phase I clean, OZ counsel engaged for structure oversight",
        probability: "8%",
      },
    ],
  },
  specialPrograms: [
    {
      name: "Opportunity Zone",
      description: "Site sits in Downtown Dallas OZ census tract; QOF equity eligible for capital gains deferral.",
    },
    {
      name: "Public Facility Corporation Lease",
      description: "Dallas Housing Finance Corp lease provides a 100% property tax exemption in exchange for workforce housing.",
    },
    {
      name: "Workforce Covenant",
      description: "58 units restricted to households earning ≤80% AMI for the term of the PFC arrangement.",
    },
  ],
};

export const assetProfileDetails = {
  sitePlan: {
    lotSize: "2.5 acres (108,900 SF)",
    buildingFootprint: "92,000 SF",
    parkingSpaces: 180,
    greenSpace: "35% of site",
    zoningDetails: {
      current: "PD-317 (SoGood Planned Development)",
      allowedFAR: "4.0",
      usedFAR: "3.3",
      heightLimit: "240 feet",
      actualHeight: "78 feet",
      setbacks: { front: "20ft", side: "15ft", rear: "20ft" },
    },
  },
  amenityDetails: [
    { name: "Resort-Style Pool", size: "3,200 SF", description: "Heated saltwater pool with cabanas overlooking the courtyard." },
    { name: "Fitness Center", size: "2,500 SF", description: "24/7 performance studio with functional training and Peloton bikes." },
    { name: "Sky Lounge", size: "1,800 SF", description: "Rooftop terrace with downtown skyline views and indoor/outdoor bar." },
    { name: "Co-Working Space", size: "1,200 SF", description: "Private focus rooms, conference space, and creators lab." },
    { name: "Pet Spa", size: "400 SF", description: "Wash stations plus on-site grooming and micro retail." },
    { name: "Package Concierge", size: "300 SF", description: "Smart lockers with cold storage for meal and grocery delivery." },
  ],
  commercialSpaces: [
    { name: "Innovation Center (GSV Holdings)", size: "30,000 SF", use: "Education / Flex Office", status: "Pre-leased" },
    { name: "Office Suite 1", size: "6,785 SF", use: "Creative Office", status: "Marketed" },
    { name: "Office Suite 2", size: "5,264 SF", use: "Professional Services", status: "Marketed" },
    { name: "Retail Bay", size: "745 SF", use: "Food & Beverage", status: "Targeting local operator" },
  ],
  unitMixDetails: {
    studios: { count: 84, avgSF: 385, rentRange: "$1,450-$1,575", deposit: "$500" },
    oneBed: { count: 24, avgSF: 759, rentRange: "$1,700-$1,875", deposit: "$750" },
    twoBed: { count: 8, avgSF: 1_120, rentRange: "$2,450-$2,650", deposit: "$1,000" },
  },
  detailedUnitMix: [
    { code: "S1", type: "Studio", units: 48, avgSF: 374 },
    { code: "S2", type: "Studio", units: 28, avgSF: 380 },
    { code: "S3", type: "Studio", units: 8, avgSF: 470 },
    { code: "A1", type: "1BR", units: 8, avgSF: 720 },
    { code: "A2", type: "1BR", units: 8, avgSF: 736 },
    { code: "A3", type: "1BR", units: 8, avgSF: 820 },
    { code: "B1", type: "2BR", units: 8, avgSF: 1_120 },
  ],
  comparableDetails: [
    {
      name: "The Hamilton",
      address: "2525 Elm St, Dallas, TX 75201",
      distance: "0.4 miles",
      yearBuilt: 2020,
      units: 329,
      occupancy: "95%",
      avgRent: "$3.05 PSF",
      lastSale: { date: "Oct 2023", price: "$118M", capRate: "4.7%" },
    },
    {
      name: "Novel Deep Ellum",
      address: "2900 Canton St, Dallas, TX 75226",
      distance: "0.6 miles",
      yearBuilt: 2022,
      units: 231,
      occupancy: "93%",
      avgRent: "$3.25 PSF",
      lastSale: { date: "Jan 2024", price: "$105M", capRate: "4.8%" },
    },
    {
      name: "The Gabriella",
      address: "2400 Main St, Dallas, TX 75201",
      distance: "0.8 miles",
      yearBuilt: 2020,
      units: 364,
      occupancy: "94%",
      avgRent: "$3.10 PSF",
      lastSale: { date: "Mar 2023", price: "$132M", capRate: "4.7%" },
    },
  ],
};

export const marketContextDetails = {
  demographicProfile: {
    oneMile: { population: 38_500, medianIncome: 72_000, medianAge: 32 },
    threeMile: { population: 174_270, medianIncome: 85_906, medianAge: 33 },
    fiveMile: { population: 410_000, medianIncome: 79_500, medianAge: 34 },
    growthTrends: {
      populationGrowth5yr: "6.9%",
      incomeGrowth5yr: "8.4%",
      jobGrowth5yr: "12.1%",
    },
    renterShare: "76.7% (3-mi)",
    bachelorsShare: "50.2% (3-mi)",
  },
  majorEmployers: [
    { name: "AT&T Discovery District", employees: 5_200, growth: "+6%", distance: "0.6 miles" },
    { name: "Baylor Univ. Medical Center", employees: 7_800, growth: "+3%", distance: "1.1 miles" },
    { name: "Dallas County Government Campus", employees: 4_200, growth: "+1%", distance: "0.8 miles" },
    { name: "JP Morgan Chase Regional HQ", employees: 5_100, growth: "+5%", distance: "1.8 miles" },
    { name: "Pegasus Park BioLabs", employees: 3_400, growth: "+8%", distance: "3.5 miles" },
  ],
  supplyAnalysis: {
    currentInventory: 12_850,
    underConstruction: 2_750,
    planned24Months: 4_100,
    averageOccupancy: "94.2%",
    deliveryByQuarter: [
      { quarter: "Q4 2024", units: 620 },
      { quarter: "Q1 2025", units: 880 },
      { quarter: "Q3 2025", units: 950 },
      { quarter: "Q1 2026", units: 760 },
      { quarter: "Q3 2026", units: 890 },
    ],
    marketNotes: "Downtown Dallas submarket shows strong fundamentals with <6,000 units delivering over next 24 months, keeping occupancy above 94%. Limited new supply in Deep Ellum/Farmers Market corridor supports rent growth.",
  },
};

// mediaAssets removed - now using Supabase storage for site-images and architectural-diagrams folders

export const financialDetails = {
  sourcesUses: {
    sources: [
      { type: "Senior Loan", amount: 18_000_000, percentage: 60.4 },
      { type: "Sponsor / PFC Equity", amount: 11_807_800, percentage: 39.6 },
    ],
    uses: [
      { type: "Land Acquisition", amount: 6_000_000, percentage: 20.1 },
      { type: "Base Construction (Hard)", amount: 16_950_000, percentage: 56.9 },
      { type: "Contingency", amount: 847_500, percentage: 2.8 },
      { type: "FF&E", amount: 580_000, percentage: 1.9 },
      { type: "Construction Fees", amount: 174_000, percentage: 0.6 },
      { type: "Architecture & Engineering", amount: 859_800, percentage: 2.9 },
      { type: "Third Party Reports", amount: 50_000, percentage: 0.2 },
      { type: "Legal & Organization", amount: 50_000, percentage: 0.2 },
      { type: "Title & Recording", amount: 75_000, percentage: 0.3 },
      { type: "Taxes During Construction", amount: 20_000, percentage: 0.1 },
      { type: "Working Capital", amount: 1_900_000, percentage: 6.4 },
      { type: "Developer Fee", amount: 678_000, percentage: 2.3 },
      { type: "PFC Structuring Fee", amount: 116_000, percentage: 0.4 },
      { type: "Financing Costs", amount: 360_000, percentage: 1.2 },
      { type: "Interest Reserve", amount: 1_147_500, percentage: 3.9 },
    ],
  },
  sponsorProfile: {
    firmName: "Hoque Global",
    yearFounded: 2008,
    totalDeveloped: "$950M+",
    totalUnits: 3_150,
    activeProjects: 5,
    principals: [
      {
        name: "Mike Hoque",
        role: "Chief Executive Officer",
        experience: "22 years",
        bio: "Founder of Hoque Global with a focus on catalytic mixed-use districts across Dallas. Led delivery of five projects within the SoGood master plan.",
        education: "BBA, University of Texas at Dallas",
        specialties: ["Master Planning", "Public / Private Partnerships", "Mixed-Use"],
        photo: "/api/placeholder/150/150/2563eb/FFFFFF?text=MH",
        achievements: [
          "Downtown Dallas Inc. Stakeholder Award",
          "Delivered 1M+ SF of adaptive reuse",
          "Chair, Dallas Regional Chamber Urban Taskforce",
        ],
      },
      {
        name: "Joel Heikenfeld",
        role: "Managing Director, ACARA",
        experience: "18 years",
        bio: "Leads capital structuring for ACARA with an emphasis on PFC-backed workforce housing investments across Texas.",
        education: "MBA, SMU Cox School of Business",
        specialties: ["Capital Markets", "Workforce Housing", "PFC Structures"],
        photo: "/api/placeholder/150/150/10B981/FFFFFF?text=JH",
        achievements: [
          "Structured $300M+ of tax-exempt executions",
          "Board Member, Dallas Housing Finance Corp",
          "ULI North Texas Housing Council",
        ],
      },
    ],
    trackRecord: [
      { project: "SoGood Phase A", year: 2023, units: 190, irr: "21.5%", status: "Completed", market: "Dallas CBD", type: "Mixed-Use" },
      { project: "Hamilton Station Lofts", year: 2021, units: 165, irr: "20.3%", status: "Completed", market: "Deep Ellum", type: "Multifamily" },
      { project: "South Side Flats", year: 2020, units: 230, irr: "22.8%", status: "Completed", market: "The Cedars", type: "Multifamily" },
      { project: "Farmers Market West", year: 2019, units: 210, irr: "19.7%", status: "Completed", market: "Farmers Market", type: "Mixed-Use" },
      { project: "Lamar Urban Lofts", year: 2018, units: 150, irr: "24.0%", status: "Completed", market: "Downtown Dallas", type: "Adaptive Reuse" },
    ],
    references: [
      { firm: "Frost Bank", contact: "Construction lending team, available upon request", relationship: "Construction Lender", years: "6+ years" },
      { firm: "Citi Community Capital", contact: "Available upon request", relationship: "Permanent / Agency Lender", years: "4+ years" },
      { firm: "Dallas Housing Finance Corp", contact: "Board liaison", relationship: "PFC Partner", years: "5+ years" },
    ],
  },
  returnProjections: {
    base: { irr: 17.5, multiple: 1.95, profitMargin: 27 },
    upside: { irr: 21.2, multiple: 2.3, profitMargin: 33 },
    downside: { irr: 13.4, multiple: 1.6, profitMargin: 18 },
  },
  t12MonthlyData: [
    {
      month: "Jan-25",
      grossPotentialRent: 150000,
      concessions: 2000,
      badDebt: 1500,
      otherIncome: 7500,
      utilities: 12000,
      repairsMaintenance: 4500,
      makeReady: 1500,
      payroll: 22000,
      managementFee: 4000,
      marketing: 2500,
      generalAdmin: 1200,
      contractServices: 3500,
      realEstateTaxes: 12500,
      insurance: 4200,
      capex: 0,
    },
    {
      month: "Feb-25",
      grossPotentialRent: 150000,
      concessions: 1500,
      badDebt: 1000,
      otherIncome: 7200,
      utilities: 11500,
      repairsMaintenance: 3800,
      makeReady: 1200,
      payroll: 22000,
      managementFee: 4000,
      marketing: 2000,
      generalAdmin: 1100,
      contractServices: 3500,
      realEstateTaxes: 12500,
      insurance: 4200,
      capex: 5000,
    },
    {
      month: "Mar-25",
      grossPotentialRent: 152000,
      concessions: 1000,
      badDebt: 1200,
      otherIncome: 7800,
      utilities: 11000,
      repairsMaintenance: 5000,
      makeReady: 2000,
      payroll: 22000,
      managementFee: 4100,
      marketing: 2500,
      generalAdmin: 1300,
      contractServices: 3500,
      realEstateTaxes: 12500,
      insurance: 4200,
      capex: 0,
    },
    {
      month: "Apr-25",
      grossPotentialRent: 152000,
      concessions: 500,
      badDebt: 1000,
      otherIncome: 8000,
      utilities: 10500,
      repairsMaintenance: 4200,
      makeReady: 1800,
      payroll: 22500,
      managementFee: 4100,
      marketing: 2500,
      generalAdmin: 1200,
      contractServices: 3800,
      realEstateTaxes: 12500,
      insurance: 4200,
      capex: 0,
    },
    {
      month: "May-25",
      grossPotentialRent: 154000,
      concessions: 500,
      badDebt: 800,
      otherIncome: 8200,
      utilities: 11000,
      repairsMaintenance: 4000,
      makeReady: 1500,
      payroll: 22500,
      managementFee: 4200,
      marketing: 3000,
      generalAdmin: 1250,
      contractServices: 3800,
      realEstateTaxes: 12500,
      insurance: 4200,
      capex: 12000,
    },
    {
      month: "Jun-25",
      grossPotentialRent: 155000,
      concessions: 0,
      badDebt: 500,
      otherIncome: 8500,
      utilities: 14000,
      repairsMaintenance: 4500,
      makeReady: 2200,
      payroll: 22500,
      managementFee: 4250,
      marketing: 3000,
      generalAdmin: 1300,
      contractServices: 3800,
      realEstateTaxes: 12500,
      insurance: 4200,
      capex: 0,
    },
    {
      month: "Jul-25",
      grossPotentialRent: 156000,
      concessions: 0,
      badDebt: 600,
      otherIncome: 9000,
      utilities: 15000,
      repairsMaintenance: 5200,
      makeReady: 2500,
      payroll: 23000,
      managementFee: 4300,
      marketing: 2500,
      generalAdmin: 1400,
      contractServices: 4000,
      realEstateTaxes: 12500,
      insurance: 4200,
      capex: 2500,
    },
    {
      month: "Aug-25",
      grossPotentialRent: 156000,
      concessions: 1000,
      badDebt: 1200,
      otherIncome: 8800,
      utilities: 15500,
      repairsMaintenance: 4800,
      makeReady: 2000,
      payroll: 23000,
      managementFee: 4300,
      marketing: 2500,
      generalAdmin: 1350,
      contractServices: 4000,
      realEstateTaxes: 12500,
      insurance: 4200,
      capex: 0,
    },
    {
      month: "Sep-25",
      grossPotentialRent: 157000,
      concessions: 500,
      badDebt: 1500,
      otherIncome: 8500,
      utilities: 13000,
      repairsMaintenance: 4500,
      makeReady: 1800,
      payroll: 23000,
      managementFee: 4350,
      marketing: 2000,
      generalAdmin: 1300,
      contractServices: 4000,
      realEstateTaxes: 12500,
      insurance: 4200,
      capex: 0,
    },
    {
      month: "Oct-25",
      grossPotentialRent: 158000,
      concessions: 500,
      badDebt: 1000,
      otherIncome: 8200,
      utilities: 12000,
      repairsMaintenance: 4200,
      makeReady: 1500,
      payroll: 23500,
      managementFee: 4400,
      marketing: 2000,
      generalAdmin: 1250,
      contractServices: 3800,
      realEstateTaxes: 12500,
      insurance: 4200,
      capex: 8000,
    },
    {
      month: "Nov-25",
      grossPotentialRent: 158000,
      concessions: 0,
      badDebt: 800,
      otherIncome: 8000,
      utilities: 11500,
      repairsMaintenance: 4000,
      makeReady: 1200,
      payroll: 23500,
      managementFee: 4400,
      marketing: 2000,
      generalAdmin: 1200,
      contractServices: 3800,
      realEstateTaxes: 12500,
      insurance: 4200,
      capex: 0,
    },
    {
      month: "Dec-25",
      grossPotentialRent: 160000,
      concessions: 2000,
      badDebt: 1000,
      otherIncome: 8500,
      utilities: 13000,
      repairsMaintenance: 5000,
      makeReady: 2500,
      payroll: 24000,
      managementFee: 4500,
      marketing: 2500,
      generalAdmin: 1500,
      contractServices: 3800,
      realEstateTaxes: 12500,
      insurance: 4200,
      capex: 0,
    },
  ],
};

export const certifications = {
  badges: [
    { name: "Opportunity Zone", status: "Qualified", icon: "shield-check" },
    { name: "Dallas PFC Tax Exemption", status: "Executed", icon: "building" },
    { name: "Workforce Housing Covenant", status: "50% ≤80% AMI", icon: "users" },
  ],
};

export const capitalStackData = {
  base: {
    totalCapitalization: 29_807_800,
    sources: [
      { type: "Senior Construction Loan", amount: 18_000_000, percentage: 60.4, rate: "SOFR + 275 bps", term: "24 + 2x6 months" },
      { type: "Sponsor / PFC Equity", amount: 11_807_800, percentage: 39.6, contribution: "Cash & ground lease", timing: "Upfront" },
    ],
    uses: [
      { type: "Land Acquisition", amount: 6_000_000, percentage: 20.1, timing: "Month 0" },
      { type: "Hard Costs", amount: 16_950_000, percentage: 56.9, timing: "Months 1-24" },
      { type: "Soft Costs", amount: 5_350_300, percentage: 18.0, timing: "Months 1-24" },
      { type: "Financing & Reserves", amount: 1_507_500, percentage: 5.1, timing: "Month 0" },
    ],
    debtTerms: {
      loanType: "Senior Construction Loan",
      lender: "National Bank (indicative)",
      rate: "8.00% floating",
      floor: "4.50%",
      term: "24 months",
      extension: "Two 6-month extensions",
      recourse: "Partial / completion",
      origination: "1.00%",
      exitFee: "0.50%",
      reserves: {
        interest: "12 months funded",
        taxInsurance: "Funded quarterly",
        capEx: "$250,000",
      },
    },
  },
  upside: {
    totalCapitalization: 30_200_000,
    sources: [
      { type: "Senior Construction Loan", amount: 18_500_000, percentage: 61.3, rate: "SOFR + 250 bps", term: "24 + 2x6 months" },
      { type: "Sponsor / PFC Equity", amount: 11_700_000, percentage: 38.7, contribution: "Cash & ground lease", timing: "Upfront" },
    ],
    uses: [
      { type: "Land Acquisition", amount: 6_000_000, percentage: 19.9, timing: "Month 0" },
      { type: "Hard Costs", amount: 17_300_000, percentage: 57.3, timing: "Months 1-22" },
      { type: "Soft Costs", amount: 5_300_000, percentage: 17.5, timing: "Months 1-22" },
      { type: "Financing & Reserves", amount: 1_600_000, percentage: 5.3, timing: "Month 0" },
    ],
    debtTerms: {
      loanType: "Senior Construction Loan",
      lender: "National Bank (indicative)",
      rate: "7.75% floating",
      floor: "4.25%",
      term: "24 months",
      extension: "Two 6-month extensions",
      recourse: "Limited",
      origination: "0.90%",
      exitFee: "0.35%",
      reserves: {
        interest: "10 months funded",
        taxInsurance: "6 months",
        capEx: "$200,000",
      },
    },
  },
  downside: {
    totalCapitalization: 30_500_000,
    sources: [
      { type: "Senior Construction Loan", amount: 17_000_000, percentage: 55.7, rate: "SOFR + 325 bps", term: "24 + 1x6 months" },
      { type: "Sponsor / PFC Equity", amount: 13_500_000, percentage: 44.3, contribution: "Cash & ground lease", timing: "Upfront" },
    ],
    uses: [
      { type: "Land Acquisition", amount: 6_000_000, percentage: 19.7, timing: "Month 0" },
      { type: "Hard Costs", amount: 17_500_000, percentage: 57.4, timing: "Months 1-26" },
      { type: "Soft Costs", amount: 5_500_000, percentage: 18.0, timing: "Months 1-26" },
      { type: "Financing & Reserves", amount: 1_500_000, percentage: 4.9, timing: "Month 0" },
    ],
    debtTerms: {
      loanType: "Senior Construction Loan",
      lender: "National Bank (indicative)",
      rate: "8.35% floating",
      floor: "4.75%",
      term: "24 months",
      extension: "One 6-month option",
      recourse: "Partial",
      origination: "1.25%",
      exitFee: "0.75%",
      reserves: {
        interest: "15 months funded",
        taxInsurance: "8 months",
        capEx: "$300,000",
      },
    },
  },
};