/**
 * Map of field dependencies for revalidation: when field A changes,
 * re-validate dependent fields B, C, D. Built from sanity check config.
 */
export const FIELD_DEPENDENCIES: Record<string, string[]> = {
	buildingType: ["numberOfStories"],
	projectPhase: ["constructionType", "purchasePrice"],
	constructionType: ["projectPhase"],
	dealStatus: ["completionDate"],
	completionDate: ["dealStatus"],
	expectedZoningChanges: ["entitlements"],
	entitlements: ["expectedZoningChanges"],
	totalResidentialUnits: [
		"studioCount",
		"oneBedCount",
		"twoBedCount",
		"threeBedCount",
		"parkingRatio",
		"averageUnitSize",
		"affordableUnitsNumber",
	],
	studioCount: ["totalResidentialUnits"],
	oneBedCount: ["totalResidentialUnits"],
	twoBedCount: ["totalResidentialUnits"],
	threeBedCount: ["totalResidentialUnits"],
	totalResidentialNRSF: ["averageUnitSize", "grossBuildingArea"],
	totalCommercialGRSF: ["grossBuildingArea", "preLeasedSF"],
	grossBuildingArea: ["totalResidentialNRSF", "totalCommercialGRSF"],
	parkingSpaces: ["parkingRatio"],
	loanAmountRequested: [
		"targetLtvPercent",
		"targetLtcPercent",
		"debtYield",
		"ltv",
		"loanFees",
		"netWorth",
		"guarantorLiquidity",
	],
	stabilizedValue: ["targetLtvPercent", "ltv"],
	totalDevelopmentCost: [
		"targetLtcPercent",
		"yieldOnCost",
		"loanAmountRequested",
		"sponsorEquity",
	],
	noiYear1: ["yieldOnCost", "debtYield", "dscr"],
	stabilizedNoiProjected: ["stabilizedValue"],
	capRate: ["stabilizedValue"],
	interestRate: ["underwritingRate", "allInRate", "dscr"],
	amortizationYears: ["dscr"],
	supplyPipeline: ["monthsOfSupply"],
	submarketAbsorption: ["monthsOfSupply", "supplyPipeline"],
	affordableHousing: ["affordableUnitsNumber"],
	affordableUnitsNumber: ["totalResidentialUnits"],
	taxExemption: ["exemptionStructure", "pfcStructuringFee"],
	environmental: ["enviroRemediation"],
	phaseIESAFinding: ["enviroRemediation"],
	enviroRemediation: ["environmental", "phaseIESAFinding"],
	landAcqClose: ["groundbreakingDate"],
	groundbreakingDate: ["landAcqClose", "completionDate"],
	firstOccupancy: ["stabilization"],
	stabilization: ["firstOccupancy"],
	totalSiteAcreage: ["buildableAcreage"],
	buildableAcreage: ["totalSiteAcreage"],
	densityBonus: ["farUtilizedPercent"],
};
