-- Create underwriting_chat_threads table
create table if not exists public.underwriting_chat_threads (
    id uuid default gen_random_uuid() primary key,
    project_id uuid not null,
    topic text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
    created_by uuid references public.profiles(id) on delete set null,
    status text default 'active' check (status in ('active', 'resolved')),
    
    constraint underwriting_chat_threads_project_id_fkey foreign key (project_id) references public.projects(id) on delete cascade
);

-- Enable RLS
alter table public.underwriting_chat_threads enable row level security;

-- Create underwriting_chat_messages table
create table if not exists public.underwriting_chat_messages (
    id bigint generated by default as identity primary key,
    thread_id uuid references public.underwriting_chat_threads(id) on delete cascade not null,
    user_id uuid, -- Nullable to support AI without foreign key constraint
    sender_type text not null check (sender_type in ('user', 'ai')),
    content text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    metadata jsonb default '{}'::jsonb
);

-- Enable RLS
alter table public.underwriting_chat_messages enable row level security;

-- Add indexes
create index if not exists idx_underwriting_threads_project_id on public.underwriting_chat_threads(project_id);
create index if not exists idx_underwriting_messages_thread_id on public.underwriting_chat_messages(thread_id);

-- RLS Policies (Basic access for project members)

-- Threads: View
create policy "Users can view underwriting threads for projects they have access to"
    on public.underwriting_chat_threads for select
    using (
        exists (
            select 1 from public.projects p
            left join public.org_members om on p.owner_org_id = om.org_id
            where p.id = underwriting_chat_threads.project_id
            and (
                -- Is advisor
                p.assigned_advisor_id = auth.uid()
                or
                -- Is org member (owner/admin)
                (om.user_id = auth.uid())
            )
        )
    );

-- Threads: Insert (Advisors and Owners)
create policy "Users can create underwriting threads for their projects"
    on public.underwriting_chat_threads for insert
    with check (
        exists (
            select 1 from public.projects p
            left join public.org_members om on p.owner_org_id = om.org_id
            where p.id = project_id
            and (
                p.assigned_advisor_id = auth.uid()
                or
                (om.user_id = auth.uid())
            )
        )
    );

-- Messages: View
create policy "Users can view messages in visible threads"
    on public.underwriting_chat_messages for select
    using (
        exists (
            select 1 from public.underwriting_chat_threads t
            where t.id = underwriting_chat_messages.thread_id
            and exists (
                select 1 from public.projects p
                left join public.org_members om on p.owner_org_id = om.org_id
                where p.id = t.project_id
                and (
                    p.assigned_advisor_id = auth.uid()
                    or
                    (om.user_id = auth.uid())
                )
            )
        )
    );

-- Messages: Insert
create policy "Users can insert messages in visible threads"
    on public.underwriting_chat_messages for insert
    with check (
        exists (
            select 1 from public.underwriting_chat_threads t
            where t.id = thread_id
            and exists (
                select 1 from public.projects p
                left join public.org_members om on p.owner_org_id = om.org_id
                where p.id = t.project_id
                and (
                    p.assigned_advisor_id = auth.uid()
                    or
                    (om.user_id = auth.uid())
                )
            )
        )
    );
